/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontMenu24.c                                          *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\GUI\Fonts\txt\FontMenu24.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontMenu24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_505C[ 72] = { /* code 505C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____X___,__X_____,________,
  ____X___,___X____,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___X____,________,________,
  ___X___X,XXXXXXX_,________,
  ___X___X,______X_,________,
  __XX___X,XXXXXXX_,________,
  __XX___X,______X_,________,
  _X_X____,________,________,
  _X_X_XXX,XXXXXXXX,X_______,
  ___X_X__,________,X_______,
  ___X___X,XXXXXXX_,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,XXXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_52A8[ 72] = { /* code 52A8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____X___,________,
  __XXXXXX,X___X___,________,
  ________,____X___,________,
  ________,_XXXXXXX,XX______,
  ________,____X___,XX______,
  ________,____X___,X_______,
  _XXXXXXX,XX__X___,X_______,
  ____X___,____X___,X_______,
  ____X___,____X___,X_______,
  ___X__X_,____X___,X_______,
  ___X___X,___X____,X_______,
  __X____X,___X____,X_______,
  __X__XXX,X__X____,X_______,
  _XXXX___,X_X_____,X_______,
  ________,__X_____,X_______,
  ________,_X___XXX,________,
  ________,X_______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_53D8[ 72] = { /* code 53D8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,X_______,________,
  ________,XX______,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ______X_,__X_____,________,
  ___X__X_,__X__X__,________,
  __XX__X_,__X___X_,________,
  _XX___X_,__X___XX,________,
  XX____X_,__X____X,X_______,
  X_______,________,X_______,
  __XXXXXX,XXXXXX__,________,
  ____X___,____X___,________,
  _____X__,__XX____,________,
  ______XX,XXX_____,________,
  _______X,XX______,________,
  ____XXX_,_XXXX___,________,
  XXXX____,_____XXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_53F3[ 72] = { /* code 53F3 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  _______X,________,________,
  _______X,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ______X_,________,________,
  _____X__,________,________,
  _____X__,________,________,
  ____X___,________,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,_______X,________,
  __XXX___,_______X,________,
  _XX_X___,_______X,________,
  XX__X___,_______X,________,
  X___X___,_______X,________,
  ____X___,_______X,________,
  ____XXXX,XXXXXXXX,________,
  ____X___,_______X,________,
  ____X___,_______X,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_59CB[ 72] = { /* code 59CB */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,___X____,________,
  ___X____,__XX____,________,
  ___X____,__X___X_,________,
  __X_____,_XX___XX,________,
  XXXXXXX_,_X_____X,________,
  __X___X_,XX_____X,X_______,
  __X___X_,XXXXXXXX,X_______,
  _X____XX,XX______,XX______,
  _X___XX_,________,_X______,
  _X___X__,________,________,
  _XX__X__,XXXXXXXX,X_______,
  ___XXX__,X_______,X_______,
  ____X___,X_______,X_______,
  ___X_X__,X_______,X_______,
  __X___X_,X_______,X_______,
  _X______,XXXXXXXX,X_______,
  X_______,X_______,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_5DE6[ 72] = { /* code 5DE6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  _______X,________,________,
  ______X_,________,________,
  __XXXXXX,XXXXXXXX,XX______,
  ______X_,________,________,
  ______X_,________,________,
  _____X__,________,________,
  _____X__,________,________,
  _____XXX,XXXXXXXX,X_______,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ___X____,__X_____,________,
  ___X____,__X_____,________,
  __X_____,__X_____,________,
  __X_____,__X_____,________,
  _X__XXXX,XXXXXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_5F00[ 72] = { /* code 5F00 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  XXXXXXXX,XXXXXXXX,XX______,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  ____X___,____X___,________,
  ___XX___,____X___,________,
  __XX____,____X___,________,
  _XX_____,____X___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_624B[ 72] = { /* code 624B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXXXX,________,
  _XXXXXXX,XXX_____,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ____XXXX,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_673A[ 72] = { /* code 673A */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,________,________,
  ___X____,XXXXXX__,________,
  ___X____,X____X__,________,
  XXXXXXX_,X____X__,________,
  ___X____,X____X__,________,
  __XX____,X____X__,________,
  __XXX___,X____X__,________,
  __XXXX__,X____X__,________,
  _X_X__X_,X____X__,________,
  _X_X____,X____X__,________,
  XX_X____,X____X__,________,
  X__X____,X____X__,_X______,
  ___X___X,_____X__,_X______,
  ___X___X,_____X__,_X______,
  ___X___X,_____X__,XX______,
  ___X__X_,_____XXX,X_______,
  ___X_XX_,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_6B62[ 72] = { /* code 6B62 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__XXXXXX,X_______,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_7535[ 72] = { /* code 7535 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _XXXXXXX,XXXXXXX_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _XXXXXXX,XXXXXXX_,________,
  _X______,X_______,________,
  ________,X_______,X_______,
  ________,X_______,X_______,
  ________,X______X,X_______,
  ________,_XXXXXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_76F8[ 72] = { /* code 76F8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,________,________,
  ___X____,XXXXXXXX,X_______,
  ___X____,X_______,X_______,
  XXXXXXX_,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,XXXXXXXX,X_______,
  __XXX___,X_______,X_______,
  __XXXX__,X_______,X_______,
  _X_X_XX_,X_______,X_______,
  _X_X__X_,X_______,X_______,
  XX_X____,XXXXXXXX,X_______,
  X__X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,X_______,X_______,
  ___X____,XXXXXXXX,X_______,
  ___X____,X_______,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_81EA[ 72] = { /* code 81EA */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  ______X_,________,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_8F6C[ 72] = { /* code 8F6C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____X__,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  _XXXXXXX,_XXXXXXX,X_______,
  ___X____,___X____,________,
  ___X_X__,___X____,________,
  __X__X__,__X_____,________,
  __X__X__,XXXXXXXX,XX______,
  _X___X__,__X_____,________,
  _XXXXXXX,_X______,________,
  _____X__,_X______,________,
  _____X_X,_XXXXXXX,X_______,
  ___XXXX_,_______X,X_______,
  _XX__X__,_XX___X_,________,
  _____X__,__XXXX__,________,
  _____X__,____XXX_,________,
  _____X__,______XX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontMenu24_901F[ 72] = { /* code 901F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _X______,___X____,________,
  _XX_____,___X____,________,
  __X__XXX,XXXXXXXX,X_______,
  __XX____,___X____,________,
  ___X____,___X____,________,
  ______XX,XXXXXXXX,________,
  XXX___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___XX,XXXXXXXX,________,
  __X___X_,__XX___X,________,
  __X_____,_XXXX___,________,
  __X____X,X__X_XX_,________,
  __X___XX,___X__XX,________,
  __X_XX__,___X____,X_______,
  _XX_____,___X____,________,
  XX_XX___,________,________,
  X___XXXX,XXXXXXXX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontMenu24_CharInfo[15] = {
   {  18,  18,  3, acGUI_FontFontMenu24_505C } /* code 505C */
  ,{  18,  18,  3, acGUI_FontFontMenu24_52A8 } /* code 52A8 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_53D8 } /* code 53D8 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_53F3 } /* code 53F3 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_59CB } /* code 59CB */
  ,{  18,  18,  3, acGUI_FontFontMenu24_5DE6 } /* code 5DE6 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_5F00 } /* code 5F00 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_624B } /* code 624B */
  ,{  18,  18,  3, acGUI_FontFontMenu24_673A } /* code 673A */
  ,{  18,  18,  3, acGUI_FontFontMenu24_6B62 } /* code 6B62 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_7535 } /* code 7535 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_76F8 } /* code 76F8 */
  ,{  18,  18,  3, acGUI_FontFontMenu24_81EA } /* code 81EA */
  ,{  18,  18,  3, acGUI_FontFontMenu24_8F6C } /* code 8F6C */
  ,{  18,  18,  3, acGUI_FontFontMenu24_901F } /* code 901F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop15 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[ 14] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop14 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[ 13] /* address of first character */
  ,&GUI_FontFontMenu24_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop13 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[ 12] /* address of first character */
  ,&GUI_FontFontMenu24_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop12 = {
   0x76F8 /* first character */
  ,0x76F8 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[ 11] /* address of first character */
  ,&GUI_FontFontMenu24_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop11 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[ 10] /* address of first character */
  ,&GUI_FontFontMenu24_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop10 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  9] /* address of first character */
  ,&GUI_FontFontMenu24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop9 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  8] /* address of first character */
  ,&GUI_FontFontMenu24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop8 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  7] /* address of first character */
  ,&GUI_FontFontMenu24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop7 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  6] /* address of first character */
  ,&GUI_FontFontMenu24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop6 = {
   0x5DE6 /* first character */
  ,0x5DE6 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  5] /* address of first character */
  ,&GUI_FontFontMenu24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop5 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  4] /* address of first character */
  ,&GUI_FontFontMenu24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop4 = {
   0x53F3 /* first character */
  ,0x53F3 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  3] /* address of first character */
  ,&GUI_FontFontMenu24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop3 = {
   0x53D8 /* first character */
  ,0x53D8 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontMenu24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop2 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontMenu24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontMenu24_Prop1 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFontMenu24_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontMenu24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontMenu24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontMenu24_Prop1}
  ,19 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

