/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MenuSong24.c                                          *
* Font:        ÐÂËÎÌå                                                *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\GUI\Fonts\txt\MenuSong24.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMenuSong24;

/* Start of unicode area <Geometric Shapes> */
GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_25B2[ 72] = { /* code 25B2, BLACK UP-POINTING TRIANGLE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,__XXX___,________,
  ________,__XXXX__,________,
  ________,_XXXXX__,________,
  ________,_XXXXXX_,________,
  ________,XXXXXXXX,________,
  ________,XXXXXXXX,________,
  _______X,XXXXXXXX,X_______,
  _______X,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_25B3[ 72] = { /* code 25B3, WHITE UP-POINTING TRIANGLE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,__X_X___,________,
  ________,__X__X__,________,
  ________,_X___X__,________,
  ________,_X____X_,________,
  ________,X______X,________,
  ________,X______X,________,
  _______X,________,X_______,
  _______X,________,X_______,
  ______X_,________,_X______,
  _____X__,________,_X______,
  _____X__,________,__X_____,
  ____X___,________,__XX____,
  ____X___,________,___X____,
  ___X____,________,____X___,
  ___X____,________,____X___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_25BC[ 72] = { /* code 25BC, BLACK DOWN-POINTING TRIANGLE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  _____XXX,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,XX______,
  ______XX,XXXXXXXX,X_______,
  _______X,XXXXXXXX,X_______,
  ________,XXXXXXXX,________,
  ________,XXXXXXX_,________,
  ________,_XXXXXX_,________,
  ________,_XXXXX__,________,
  ________,__XXXX__,________,
  ________,__XXX___,________,
  ________,___XX___,________,
  ________,___X____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_25BD[ 72] = { /* code 25BD, WHITE DOWN-POINTING TRIANGLE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___X____,________,___XX___,
  ____X___,________,___X____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  ______X_,________,_X______,
  ______X_,________,XX______,
  _______X,________,X_______,
  _______X,X______X,________,
  ________,X______X,________,
  ________,_X____X_,________,
  ________,_X___XX_,________,
  ________,__X__X__,________,
  ________,__XXX___,________,
  ________,___XX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_505C[ 72] = { /* code 505C */
  ________,________,________,
  ________,_____X__,________,
  _____XX_,_____XX_,________,
  _____X__,______X_,____X___,
  _____X_X,XXXXXXXX,XXXXXX__,
  ____XX__,________,________,
  ____X___,__XXXXXX,XXX_____,
  ____XX__,__X_____,__X_____,
  ___XX___,__X_____,__X_____,
  ___XX___,__XXXXXX,XXX_____,
  __X_X___,__X_____,__X_____,
  __X_X___,XXXXXXXX,XXXXXX__,
  _X__X__X,________,____X___,
  ____X__X,________,____X___,
  ____X___,_XXXXXXX,XXXX____,
  ____X___,______XX,________,
  ____X___,______XX,________,
  ____X___,______XX,________,
  ____X___,______XX,________,
  ____X___,______XX,________,
  ____X___,______XX,________,
  ____X___,____XXX_,________,
  ____X___,_____XX_,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_52A8[ 72] = { /* code 52A8 */
  ________,________,________,
  ________,________,________,
  ________,_______X,________,
  ________,_______X,________,
  ________,_X_____X,________,
  __XXXXXX,XXX____X,________,
  ________,_______X,________,
  ________,____XXXX,XXXXXX__,
  ________,_______X,____XX__,
  _XXXXXXX,XXXX___X,____XX__,
  ______X_,_______X,____XX__,
  _____XX_,_______X,____XX__,
  _____X__,_______X,____X___,
  ____XX__,X______X,____X___,
  ____X___,_X____XX,____X___,
  ___X____,_XX___X_,____X___,
  ___X____,__X___X_,____X___,
  __XXXXXX,XXXX_X__,____X___,
  __XX____,___XXX__,____X___,
  ________,____X___,____X___,
  ________,___X___X,X__XX___,
  ________,_XX_____,_XXX____,
  ________,X_______,__X_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_53CC[ 72] = { /* code 53CC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__X_____,____X___,
  __XXXXXX,XXXXXXXX,XXXXX___,
  ________,__X__X__,___XX___,
  ________,__X__X__,___X____,
  ________,_XX___X_,___X____,
  ____X___,_X____X_,___X____,
  ____X___,_X____X_,__XX____,
  _____X__,XX____X_,__XX____,
  ______X_,X_____X_,__X_____,
  _______X,X______X,__X_____,
  _______X,X______X,_XX_____,
  ______XX,XX_____X,XX______,
  ______X_,_XX_____,XX______,
  _____X__,_XX_____,XX______,
  ____X___,__X____X,_X______,
  ___X____,__X___XX,_XX_____,
  __X_____,_____XX_,__XX____,
  _X______,____X___,___XXX__,
  ________,__XX____,____XX__,
  ________,_X______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_53D8[ 72] = { /* code 53D8 */
  ________,________,________,
  ________,__X_____,________,
  ________,___XX___,________,
  ________,___XX___,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_X____X_,________,
  ________,_X____X_,________,
  ______XX,_X____X_,XX______,
  _____XX_,_X____X_,__X_____,
  ____XX__,_X____X_,___XX___,
  ____X___,_X____X_,____XX__,
  ___X____,_X____X_,_X___X__,
  __X_XXXX,XXXXXXXX,XXX_____,
  ________,X_______,XX______,
  ________,_X_____X,X_______,
  ________,_X____XX,________,
  ________,__X___X_,________,
  ________,___XXX__,________,
  ________,___XX___,________,
  ________,__XX_XX_,________,
  ________,XX_____X,XX______,
  _____XXX,________,_XXXXXX_,
  __XXX___,________,___XX___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_53F3[ 72] = { /* code 53F3 */
  ________,________,________,
  ________,________,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,__XX____,________,
  ________,__X_____,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_XX_____,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,X_______,________,
  ________,X_______,__X_____,
  _______X,XXXXXXXX,XXXX____,
  ______XX,X_______,__X_____,
  ______X_,X_______,__X_____,
  _____X__,X_______,__X_____,
  ____X___,X_______,__X_____,
  ___X____,X_______,__X_____,
  __X_____,X_______,__X_____,
  _X______,X_______,__X_____,
  ________,XXXXXXXX,XXX_____,
  ________,X_______,__X_____,
  ________,X_______,__X_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_5411[ 72] = { /* code 5411 */
  ________,________,________,
  ________,__X_____,________,
  ________,__XX____,________,
  ________,__X_____,________,
  ________,_X______,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ___XX___,XXXXXXXX,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,XXXXXXXX,___XX___,
  ___XX___,X______X,___XX___,
  ___XX___,X_______,___XX___,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ___XX___,_______X,XXXXX___,
  ___XX___,________,__XX____,
  ___X____,________,___X____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_59CB[ 72] = { /* code 59CB */
  ________,________,________,
  _____X__,_______X,________,
  _____XX_,_______X,X_______,
  _____XX_,______XX,________,
  _____X__,______X_,________,
  _____X__,______X_,________,
  _XXXXXXX,XX___X__,__X_____,
  ____X___,_X___X__,___XX___,
  ____X___,XX__X___,____XX__,
  ____X___,XX_XX___,_XXXXX__,
  ___XX___,X__XXXXX,X____X__,
  ___X____,X_______,_____X__,
  ___X____,X_______,________,
  ___X___X,X___XXXX,XXXXX___,
  __X____X,____XX__,____X___,
  ___XXX_X,____XX__,____X___,
  _____XXX,____XX__,____X___,
  ______XX,X___XX__,____X___,
  _____XX_,XX__XX__,____X___,
  ____XX__,_X__XX__,____X___,
  ____X___,____XXXX,XXXXX___,
  __XX____,____XX__,____X___,
  _X______,____X___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_5DE6[ 72] = { /* code 5DE6 */
  ________,________,________,
  ________,_X______,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,_X______,___X____,
  __XXXXXX,XXXXXXXX,XXXXX___,
  ________,_X______,________,
  ________,XX______,________,
  ________,X_______,________,
  ________,X_______,________,
  _______X,X_______,________,
  _______X,________,________,
  _______X,XXXXXXXX,XXX_____,
  ______X_,_____X__,________,
  ______X_,_____X__,________,
  _____X__,_____X__,________,
  _____X__,_____X__,________,
  ____X___,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  __X_____,_____X__,____X___,
  _X___XXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_5F00[ 72] = { /* code 5F00 */
  ________,________,________,
  ________,________,________,
  ________,________,___X____,
  __XXXXXX,XXXXXXXX,XXXXX___,
  ________,X______X,________,
  ________,X______X,________,
  ________,X______X,________,
  ________,X______X,________,
  ________,X______X,________,
  ________,X______X,________,
  ________,X______X,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,X______X,________,
  ________,X______X,________,
  ________,X______X,________,
  _______X,X______X,________,
  _______X,_______X,________,
  _______X,_______X,________,
  ______X_,_______X,________,
  _____XX_,_______X,________,
  ____XX__,_______X,________,
  ___X____,_______X,________,
  __X_____,_______X,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_5F0F[ 72] = { /* code 5F0F */
  ________,________,________,
  ________,_____X__,________,
  ________,_____XX_,_X______,
  ________,_____XX_,__XX____,
  ________,_____XX_,__XX____,
  ________,_____XX_,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,_____XX_,________,
  ________,_____XX_,________,
  ________,______X_,________,
  ________,______X_,________,
  __XXXXXX,XXXX__X_,________,
  _______X,______X_,________,
  _______X,______XX,________,
  _______X,______XX,________,
  _______X,_______X,________,
  _______X,_______X,X_______,
  _______X,________,X____X__,
  _______X,_XXXX___,XX___X__,
  ______XX,X_______,_XX__X__,
  __XXXX__,________,__XXXX__,
  __XX____,________,___XXX__,
  ________,________,_____XX_,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_624B[ 72] = { /* code 624B */
  ________,________,________,
  ________,________,________,
  ________,________,_XX_____,
  ________,____XXXX,XXXX____,
  ___XXXXX,XXXX____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,__X_____,
  ___XXXXX,XXXXXXXX,XXXX____,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  _______X,X__X____,________,
  ________,_XXX____,________,
  ________,__X_____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_62C9[ 72] = { /* code 62C9 */
  ________,________,________,
  ________,________,________,
  ______X_,______X_,________,
  ______X_,_______X,________,
  ______X_,_______X,X_______,
  ______X_,_______X,X_______,
  _XXXXXXX,XX______,____X___,
  ______X_,__XXXXXX,XXXXXX__,
  ______X_,________,________,
  ______X_,________,________,
  ______X_,_X______,__X_____,
  ______XX,X___X___,__XX____,
  _____XX_,____X___,__X_____,
  ___XX_X_,____XX__,__X_____,
  _XXX__X_,_____X__,_XX_____,
  ______X_,_____X__,_X______,
  ______X_,_____XX_,_X______,
  ______X_,_____XX_,_X______,
  ______X_,_____X__,X_______,
  ______X_,________,X_______,
  __XX_XX_,________,X____X__,
  ____XXX_,XXXXXXXX,XXXXXXX_,
  _____X__,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_673A[ 72] = { /* code 673A */
  ________,________,________,
  _____X__,________,________,
  _____XX_,________,________,
  _____X__,___XXXXX,XXX_____,
  _____X__,___XX___,_X______,
  _____X__,___XX___,_X______,
  _____X__,___XX___,_X______,
  _XXXXXXX,XX_XX___,_X______,
  _____X__,___XX___,_X______,
  _____X__,___XX___,_X______,
  ____XXX_,___XX___,_X______,
  ____XX_X,X__XX___,_X______,
  ____XX__,XX_XX___,_X______,
  ____XX__,_X_XX___,_X______,
  ___X_X__,___XX___,_X______,
  ___X_X__,___XX___,_X______,
  __X__X__,___X____,_X______,
  __X__X__,___X____,_X______,
  _X___X__,__XX____,_X___X__,
  _____X__,__X_____,_X___X__,
  _____XX_,_XX_____,_X___X__,
  _____XX_,_X______,_XX__XX_,
  _____XX_,X_______,_XXXXX__,
  _____X_X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_6837[ 72] = { /* code 6837 */
  ________,________,________,
  _____X__,________,__X_____,
  _____X__,___X____,__XX____,
  _____X__,____XX__,_XX_____,
  _____X__,____XX__,_X______,
  _____X__,X____X__,X___X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  _____X__,_______X,________,
  _____X__,_______X,________,
  ____XX__,_______X,________,
  ____XXXX,__XXXXXX,XXXXX___,
  ____XX_X,X______X,________,
  ___X_X__,X______X,________,
  ___X_X__,X______X,________,
  __X__X__,_______X,________,
  __X__X__,XXXXXXXX,XXXXXX__,
  _X___X__,_______X,________,
  _____X__,_______X,________,
  _____X__,_______X,________,
  _____X__,_______X,________,
  _____X__,_______X,________,
  _____X__,_______X,________,
  _____X__,_______X,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_6A21[ 72] = { /* code 6A21 */
  ________,________,________,
  _____X__,____X___,_X______,
  _____X__,____XX__,_X______,
  _____X__,____XX__,_X______,
  _____X__,XXXXXXXX,XXXXXX__,
  _____X__,X___XX__,_X______,
  _XXXXXXX,X___XX__,_X______,
  _____X__,___XXXXX,XXXXX___,
  ____XX__,___X____,___X____,
  ____XXX_,___X____,___X____,
  ____XX_X,___XXXXX,XXXX____,
  ___XXX_X,X__X____,___X____,
  ___X_X__,X__X____,___X____,
  ___X_X__,___XXXXX,XXXX____,
  __X__X__,___X__XX,___X____,
  __X__X__,______X_,________,
  _X___X__,XXXXXXXX,XXXXXX__,
  _____X__,______X_,X_______,
  _____X__,_____XX_,X_______,
  _____X__,_____X__,_X______,
  _____X__,____X___,__XX____,
  _____X__,__XX____,___XXXX_,
  _____X__,XX______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_6B62[ 72] = { /* code 6B62 */
  ________,________,________,
  ________,____X___,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,___X____,
  ______X_,____XXXX,XXXXX___,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,________,
  ______X_,____XX__,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_7535[ 72] = { /* code 7535 */
  ________,________,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,__X_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,___X____,__X_____,
  ____X___,___X____,________,
  ________,___X____,_____X__,
  ________,___X____,_____X__,
  ________,___X____,_____X__,
  ________,___X____,____XX__,
  ________,___XXXXX,XXXXXX__,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_81EA[ 72] = { /* code 81EA */
  ________,________,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  _____XXX,XXXXXXXX,XXXX____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  _____XXX,XXXXXXXX,XXX_____,
  _____X__,________,__X_____,
  _____X__,________,__X_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_8F6C[ 72] = { /* code 8F6C */
  ________,________,________,
  _____X__,________,X_______,
  _____XX_,________,X_______,
  _____X__,_______X,X_______,
  _____X__,_______X,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ____X___,_______X,________,
  ____X___,______XX,________,
  ___XX_XX,______XX,________,
  ___X__X_,______X_,_____X__,
  ___X__X_,_XXXXXXX,XXXXXX__,
  __XXXXXX,XXX__XX_,________,
  ______X_,_____X__,________,
  ______X_,____XXXX,XXXX____,
  ______X_,_____X__,__XXX___,
  ______X_,XXX_____,__X_____,
  ____XXXX,________,_XX_____,
  _XXX__X_,____X___,_X______,
  ______X_,_____XX_,X_______,
  ______X_,_______X,X_______,
  ______X_,________,XXX_____,
  ______X_,________,_XX_____,
  ______X_,________,__X_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_901F[ 72] = { /* code 901F */
  ________,________,________,
  ________,________,________,
  ________,______X_,________,
  ________,______X_,________,
  ___XX___,______X_,____X___,
  ____XX_X,XXXXXXXX,XXXXXX__,
  ____XX__,______X_,________,
  ________,______X_,________,
  ________,_XXXXXXX,XXXXX___,
  ________,_XX___X_,___X____,
  _XXXXXX_,_XX___X_,___X____,
  _____X__,_XX___X_,___X____,
  _____X__,_XXXXXXX,XXXX____,
  _____X__,_XX__XX_,___X____,
  _____X__,____XXX_,________,
  _____X__,____X_XX,XX______,
  _____X__,___X__X_,_XXX____,
  _____X__,__X___X_,___XX___,
  _____X__,XX____X_,____X___,
  ___XX_XX,______X_,________,
  __XX___X,______X_,________,
  __X_____,XXXX____,___XXXX_,
  ________,___XXXXX,XXXXX___,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_91C7[ 72] = { /* code 91C7 */
  ________,________,________,
  ________,________,__XX____,
  ________,_____XXX,XXXXX___,
  ___XXXXX,XXXXX___,________,
  ________,__X_____,__X_____,
  ________,__XX____,__XX____,
  ____XX__,___XX___,_XX_____,
  _____XX_,___XX___,_X______,
  ______X_,____X___,X_______,
  ______X_,____X___,X_______,
  ______X_,___XX__X,________,
  ________,___XX_X_,_____X__,
  _XXXXXXX,XXXXXXXX,XXXXXX__,
  ________,__XXXX__,________,
  ________,_XXXXX__,________,
  ________,_X_XX_X_,________,
  ________,X__XX__X,________,
  _______X,X__XX__X,________,
  ______XX,___XX___,X_______,
  _____XX_,___XX___,_X______,
  ____X___,___XX___,_XXX____,
  ___X____,___XX___,___XXXX_,
  _XX_____,___XX___,____X___,
  ________,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuSong24_9525[ 72] = { /* code 9525 */
  ________,________,________,
  ________,____X__X,________,
  ____XX__,____XX__,XX______,
  ____XX__,____X___,XX______,
  ____X___,___XX___,_X__X___,
  ___XXXXX,XX_XXXXX,XXXXXX__,
  ___X____,__XX____,X_______,
  ___X___X,__XX____,X_______,
  __XXXXXX,X_XX____,X___X___,
  __X__X__,_X_XXXXX,XXXXXX__,
  _X___X__,X__X____,X_______,
  _____X__,___X____,X_______,
  _____X__,___X____,X_______,
  _XXXXXXX,X__X____,X___X___,
  _____X__,___XXXXX,XXXXXX__,
  _____X__,___X____,X_______,
  _____X__,___X____,X_______,
  _____X__,___X____,X_______,
  _____X_X,X__X____,X____X__,
  _____XX_,___XXXXX,XXXXXX__,
  ____XX__,___X____,________,
  _____X__,___X____,________,
  ________,___X____,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMenuSong24_CharInfo[26] = {
   {  24,  24,  3, acGUI_FontMenuSong24_25B2 } /* code 25B2 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_25B3 } /* code 25B3 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_25BC } /* code 25BC */
  ,{  24,  24,  3, acGUI_FontMenuSong24_25BD } /* code 25BD */
  ,{  24,  24,  3, acGUI_FontMenuSong24_505C } /* code 505C */
  ,{  24,  24,  3, acGUI_FontMenuSong24_52A8 } /* code 52A8 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_53CC } /* code 53CC */
  ,{  24,  24,  3, acGUI_FontMenuSong24_53D8 } /* code 53D8 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_53F3 } /* code 53F3 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_5411 } /* code 5411 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_59CB } /* code 59CB */
  ,{  24,  24,  3, acGUI_FontMenuSong24_5DE6 } /* code 5DE6 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_5F00 } /* code 5F00 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_5F0F } /* code 5F0F */
  ,{  24,  24,  3, acGUI_FontMenuSong24_624B } /* code 624B */
  ,{  24,  24,  3, acGUI_FontMenuSong24_62C9 } /* code 62C9 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_673A } /* code 673A */
  ,{  24,  24,  3, acGUI_FontMenuSong24_6837 } /* code 6837 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_6A21 } /* code 6A21 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_6B62 } /* code 6B62 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_7535 } /* code 7535 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_81EA } /* code 81EA */
  ,{  24,  24,  3, acGUI_FontMenuSong24_8F6C } /* code 8F6C */
  ,{  24,  24,  3, acGUI_FontMenuSong24_901F } /* code 901F */
  ,{  24,  24,  3, acGUI_FontMenuSong24_91C7 } /* code 91C7 */
  ,{  24,  24,  3, acGUI_FontMenuSong24_9525 } /* code 9525 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop24 = {
   0x9525 /* first character */
  ,0x9525 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 25] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop23 = {
   0x91C7 /* first character */
  ,0x91C7 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 24] /* address of first character */
  ,&GUI_FontMenuSong24_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop22 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 23] /* address of first character */
  ,&GUI_FontMenuSong24_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop21 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 22] /* address of first character */
  ,&GUI_FontMenuSong24_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop20 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 21] /* address of first character */
  ,&GUI_FontMenuSong24_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop19 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 20] /* address of first character */
  ,&GUI_FontMenuSong24_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop18 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 19] /* address of first character */
  ,&GUI_FontMenuSong24_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop17 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 18] /* address of first character */
  ,&GUI_FontMenuSong24_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop16 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 17] /* address of first character */
  ,&GUI_FontMenuSong24_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop15 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 16] /* address of first character */
  ,&GUI_FontMenuSong24_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop14 = {
   0x62C9 /* first character */
  ,0x62C9 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 15] /* address of first character */
  ,&GUI_FontMenuSong24_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop13 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 14] /* address of first character */
  ,&GUI_FontMenuSong24_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop12 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 13] /* address of first character */
  ,&GUI_FontMenuSong24_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop11 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 12] /* address of first character */
  ,&GUI_FontMenuSong24_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop10 = {
   0x5DE6 /* first character */
  ,0x5DE6 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 11] /* address of first character */
  ,&GUI_FontMenuSong24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop9 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[ 10] /* address of first character */
  ,&GUI_FontMenuSong24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop8 = {
   0x5411 /* first character */
  ,0x5411 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  9] /* address of first character */
  ,&GUI_FontMenuSong24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop7 = {
   0x53F3 /* first character */
  ,0x53F3 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  8] /* address of first character */
  ,&GUI_FontMenuSong24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop6 = {
   0x53D8 /* first character */
  ,0x53D8 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  7] /* address of first character */
  ,&GUI_FontMenuSong24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop5 = {
   0x53CC /* first character */
  ,0x53CC /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  6] /* address of first character */
  ,&GUI_FontMenuSong24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop4 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  5] /* address of first character */
  ,&GUI_FontMenuSong24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop3 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  4] /* address of first character */
  ,&GUI_FontMenuSong24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop2 = {
   0x25BC /* first character */
  ,0x25BD /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  2] /* address of first character */
  ,&GUI_FontMenuSong24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuSong24_Prop1 = {
   0x25B2 /* first character */
  ,0x25B3 /* last character  */
  ,&GUI_FontMenuSong24_CharInfo[  0] /* address of first character */
  ,&GUI_FontMenuSong24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMenuSong24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMenuSong24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

