/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MenuMSBlack24.c                                       *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Desktop\GUI\Fonts\txt\MenuMSBlack24.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMenuMSBlack24;

/* Start of unicode area <Geometric Shapes> */
GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_25B2[ 72] = { /* code 25B2, BLACK UP-POINTING TRIANGLE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,XX______,________,
  ________,XX______,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  ______XX,XXXX____,________,
  ______XX,XXXX____,________,
  _____XXX,XXXXX___,________,
  _____XXX,XXXXX___,________,
  ____XXXX,XXXXXX__,________,
  ____XXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXX_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_25BC[ 72] = { /* code 25BC, BLACK DOWN-POINTING TRIANGLE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXX__,________,
  ____XXXX,XXXXXX__,________,
  _____XXX,XXXXX___,________,
  _____XXX,XXXXX___,________,
  ______XX,XXXX____,________,
  ______XX,XXXX____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  ________,XX______,________,
  ________,XX______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_505C[ 72] = { /* code 505C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____X___,__X_____,________,
  ____X___,___X____,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___X____,________,________,
  ___X___X,XXXXXXX_,________,
  ___X___X,______X_,________,
  __XX___X,XXXXXXX_,________,
  __XX___X,______X_,________,
  _X_X____,________,________,
  _X_X_XXX,XXXXXXXX,X_______,
  ___X_X__,________,X_______,
  ___X___X,XXXXXXX_,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,XXXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_52A8[ 72] = { /* code 52A8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____X___,________,
  __XXXXXX,X___X___,________,
  ________,____X___,________,
  ________,_XXXXXXX,XX______,
  ________,____X___,XX______,
  ________,____X___,X_______,
  _XXXXXXX,XX__X___,X_______,
  ____X___,____X___,X_______,
  ____X___,____X___,X_______,
  ___X__X_,____X___,X_______,
  ___X___X,___X____,X_______,
  __X____X,___X____,X_______,
  __X__XXX,X__X____,X_______,
  _XXXX___,X_X_____,X_______,
  ________,__X_____,X_______,
  ________,_X___XXX,________,
  ________,X_______,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_53CC[ 72] = { /* code 53CC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  XXXXXXXX,_XXXXXXX,X_______,
  _______X,_X______,X_______,
  X______X,_X______,X_______,
  _X_____X,_X______,X_______,
  _XX___X_,_XX____X,________,
  __X___X_,__X____X,________,
  ___X_XX_,__X____X,________,
  ___XXX__,__XX__X_,________,
  ____XX__,___X__X_,________,
  ____XX__,___XXX__,________,
  ___XXXX_,____XX__,________,
  ___X__X_,____XX__,________,
  __X___XX,___X_XX_,________,
  _X_____X,_XX___XX,________,
  X_______,XX_____X,X_______,
  ______XX,________,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_53D8[ 72] = { /* code 53D8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,X_______,________,
  ________,XX______,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ______X_,__X_____,________,
  ___X__X_,__X__X__,________,
  __XX__X_,__X___X_,________,
  _XX___X_,__X___XX,________,
  XX____X_,__X____X,X_______,
  X_______,________,X_______,
  __XXXXXX,XXXXXX__,________,
  ____X___,____X___,________,
  _____X__,__XX____,________,
  ______XX,XXX_____,________,
  _______X,XX______,________,
  ____XXX_,_XXXX___,________,
  XXXX____,_____XXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_53F3[ 72] = { /* code 53F3 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  _______X,________,________,
  _______X,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ______X_,________,________,
  _____X__,________,________,
  _____X__,________,________,
  ____X___,________,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,_______X,________,
  __XXX___,_______X,________,
  _XX_X___,_______X,________,
  XX__X___,_______X,________,
  X___X___,_______X,________,
  ____X___,_______X,________,
  ____XXXX,XXXXXXXX,________,
  ____X___,_______X,________,
  ____X___,_______X,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_5411[ 72] = { /* code 5411 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  _______X,________,________,
  _______X,________,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,_______X,________,
  __X_____,_______X,________,
  __X_____,_______X,________,
  __X___XX,XXXX___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___XX,XXXX___X,________,
  __X___X_,_______X,________,
  __X_____,_______X,________,
  __X_____,_______X,________,
  __X_____,___XXXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_5929[ 72] = { /* code 5929 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,X_______,
  _______X,X_______,________,
  _______X,_X______,________,
  ______XX,_X______,________,
  ______X_,_XX_____,________,
  _____XX_,__X_____,________,
  ____XX__,___X____,________,
  ___XX___,____X___,________,
  _XXX____,_____XX_,________,
  XX______,_______X,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_59CB[ 72] = { /* code 59CB */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,___X____,________,
  ___X____,__XX____,________,
  ___X____,__X___X_,________,
  __X_____,_XX___XX,________,
  XXXXXXX_,_X_____X,________,
  __X___X_,XX_____X,X_______,
  __X___X_,XXXXXXXX,X_______,
  _X____XX,XX______,XX______,
  _X___XX_,________,_X______,
  _X___X__,________,________,
  _XX__X__,XXXXXXXX,X_______,
  ___XXX__,X_______,X_______,
  ____X___,X_______,X_______,
  ___X_X__,X_______,X_______,
  __X___X_,X_______,X_______,
  _X______,XXXXXXXX,X_______,
  X_______,X_______,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_5DE6[ 72] = { /* code 5DE6 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  _______X,________,________,
  ______X_,________,________,
  __XXXXXX,XXXXXXXX,XX______,
  ______X_,________,________,
  ______X_,________,________,
  _____X__,________,________,
  _____X__,________,________,
  _____XXX,XXXXXXXX,X_______,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ___X____,__X_____,________,
  ___X____,__X_____,________,
  __X_____,__X_____,________,
  __X_____,__X_____,________,
  _X__XXXX,XXXXXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_5F00[ 72] = { /* code 5F00 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  XXXXXXXX,XXXXXXXX,XX______,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  ____X___,____X___,________,
  ___XX___,____X___,________,
  __XX____,____X___,________,
  _XX_____,____X___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_5F0F[ 72] = { /* code 5F0F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__X__X__,________,
  ________,__X___XX,________,
  ________,__X___X_,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  XXXXXXXX,X_X_____,________,
  ____X___,___X____,________,
  ____X___,___X____,________,
  ____X___,___X____,________,
  ____X___,___X____,________,
  ____X___,___XX___,_X______,
  ____X_XX,XX__X___,_X______,
  __XXXX__,____XX__,_X______,
  XX______,_____XX_,X_______,
  ________,______XX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_624B[ 72] = { /* code 624B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,___XXXXX,________,
  _XXXXXXX,XXX_____,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ____XXXX,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_62C9[ 72] = { /* code 62C9 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,___X____,________,
  ___X____,___XX___,________,
  ___X____,____X___,________,
  ___X___X,XXXXXXXX,X_______,
  XXXXXX__,________,________,
  ___X____,X______X,________,
  ___X____,X______X,________,
  ___X____,_X_____X,________,
  ___X_XX_,_X____X_,________,
  __XXX___,_X____X_,________,
  XX_X____,_X____X_,________,
  ___X____,__X___X_,________,
  ___X____,__X__X__,________,
  ___X____,__X__X__,________,
  ___X____,_____X__,________,
  ___X__XX,XXXXXXXX,XX______,
  XXXX____,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_673A[ 72] = { /* code 673A */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,________,________,
  ___X____,XXXXXX__,________,
  ___X____,X____X__,________,
  XXXXXXX_,X____X__,________,
  ___X____,X____X__,________,
  __XX____,X____X__,________,
  __XXX___,X____X__,________,
  __XXXX__,X____X__,________,
  _X_X__X_,X____X__,________,
  _X_X____,X____X__,________,
  XX_X____,X____X__,________,
  X__X____,X____X__,_X______,
  ___X___X,_____X__,_X______,
  ___X___X,_____X__,_X______,
  ___X___X,_____X__,XX______,
  ___X__X_,_____XXX,X_______,
  ___X_XX_,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_6837[ 72] = { /* code 6837 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,X_______,________,
  ___X____,_X_____X,________,
  ___X____,_XX___X_,________,
  ___X____,__X__X__,________,
  XXXXXX_X,XXXXXXXX,X_______,
  ___X____,____X___,________,
  __XX____,____X___,________,
  __XXX___,____X___,________,
  __XXXX_X,XXXXXXXX,X_______,
  _X_X_XX_,____X___,________,
  _X_X__X_,____X___,________,
  X__X____,____X___,________,
  X__X__XX,XXXXXXXX,XX______,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_6A21[ 72] = { /* code 6A21 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,_X___X__,________,
  ___X____,_X___X__,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,_X___X__,________,
  XXXXXX__,_X___X__,________,
  ___X___X,XXXXXXXX,________,
  __XX___X,_______X,________,
  __XXX__X,XXXXXXXX,________,
  _XXX_X_X,_______X,________,
  _X_X___X,XXXXXXXX,________,
  XX_X___X,___X___X,________,
  X__X____,___X____,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,__XXX___,________,
  ___X____,_XX_X___,________,
  ___X___X,X____XX_,________,
  ___X_XX_,_______X,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_6B62[ 72] = { /* code 6B62 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__XXXXXX,X_______,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  _XXXXXXX,XXXXXXXX,XX______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_715C[ 72] = { /* code 715C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __X_____,________,________,
  __X____X,XXXXXXXX,________,
  __X____X,_______X,________,
  X_X__X_X,_______X,________,
  X_X__X_X,XXXXXXXX,________,
  XXX__X_X,_______X,________,
  _XX_X__X,_______X,________,
  _XX_X__X,XXXXXXXX,________,
  __X____X,__X____X,________,
  __X_____,___X____,________,
  __XX__XX,XXXXXXXX,X_______,
  __XXX___,________,________,
  __X_XX_X,______X_,________,
  _X___X__,X____X__,________,
  _X______,XX___X__,________,
  XX______,_X__X___,________,
  X____XXX,XXXXXXXX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_724C[ 72] = { /* code 724C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____X___,___X____,________,
  _X__X___,__X_____,________,
  _X__X__X,XXXXXXXX,________,
  _X__X__X,___X___X,________,
  _X__X__X,___X___X,________,
  _X__X__X,XXXXXXXX,________,
  _XXXXX_X,___X___X,________,
  _X_____X,___X___X,________,
  _X_____X,___X___X,________,
  _X_____X,XXXXXXXX,________,
  _XXXX___,__X____X,________,
  _X__X___,XX__X___,________,
  _X__X__X,X___X___,________,
  _X__X_XX,XXXXXXXX,X_______,
  _X__X___,____X___,________,
  X___X___,____X___,________,
  X___X___,____X___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_7535[ 72] = { /* code 7535 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXX_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _XXXXXXX,XXXXXXX_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _X______,X_____X_,________,
  _XXXXXXX,XXXXXXX_,________,
  _X______,X_______,________,
  ________,X_______,X_______,
  ________,X_______,X_______,
  ________,X______X,X_______,
  ________,_XXXXXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_81EA[ 72] = { /* code 81EA */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,________,________,
  ______X_,________,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_8F6C[ 72] = { /* code 8F6C */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _____X__,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  _XXXXXXX,_XXXXXXX,X_______,
  ___X____,___X____,________,
  ___X_X__,___X____,________,
  __X__X__,__X_____,________,
  __X__X__,XXXXXXXX,XX______,
  _X___X__,__X_____,________,
  _XXXXXXX,_X______,________,
  _____X__,_X______,________,
  _____X_X,_XXXXXXX,X_______,
  ___XXXX_,_______X,X_______,
  _XX__X__,_XX___X_,________,
  _____X__,__XXXX__,________,
  _____X__,____XXX_,________,
  _____X__,______XX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_901F[ 72] = { /* code 901F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _X______,___X____,________,
  _XX_____,___X____,________,
  __X__XXX,XXXXXXXX,X_______,
  __XX____,___X____,________,
  ___X____,___X____,________,
  ______XX,XXXXXXXX,________,
  XXX___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___XX,XXXXXXXX,________,
  __X___X_,__XX___X,________,
  __X_____,_XXXX___,________,
  __X____X,X__X_XX_,________,
  __X___XX,___X__XX,________,
  __X_XX__,___X____,X_______,
  _XX_____,___X____,________,
  XX_XX___,________,________,
  X___XXXX,XXXXXXXX,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_91C7[ 72] = { /* code 91C7 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____XXXX,________,
  __XXXXXX,XXXX____,________,
  _______X,_______X,________,
  __X____X,X_____XX,________,
  __XX____,X_____X_,________,
  ___X____,_X___X__,________,
  ___XX___,_X__XX__,________,
  ____X___,X___X___,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _______X,XX______,________,
  ______X_,X_X_____,________,
  _____X__,X__X____,________,
  ___XX___,X___XX__,________,
  __XX____,X_____XX,________,
  XX______,X_______,XX______,
  ________,X_______,________,
  ________,X_______,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_9525[ 72] = { /* code 9525 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __X_____,_X__X___,________,
  __X_____,XX__X___,________,
  _X______,X____X__,________,
  _XXXXX_X,X____X__,________,
  _X_____X,XXXXXXXX,X_______,
  X_____XX,____X___,________,
  XXXXX_XX,____X___,________,
  __X__X_X,XXXXXXXX,X_______,
  __X____X,____X___,________,
  __X____X,____X___,________,
  XXXXXX_X,____X___,________,
  __X____X,XXXXXXXX,X_______,
  __X____X,____X___,________,
  __X____X,____X___,________,
  __X__X_X,____X___,________,
  __XXX__X,XXXXXXXX,X_______,
  _XX____X,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMenuMSBlack24_9738[ 72] = { /* code 9738 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,________,
  ________,XX______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _X______,XX______,X_______,
  ___XXXXX,XXXXXXX_,________,
  __X_____,XX______,________,
  XXXXXXXX,XXXXXXXX,________,
  __X____X,__X____X,________,
  __XXXXXX,__X____X,________,
  _____X__,__XXXXXX,________,
  __XXXXXX,X_X____X,________,
  __X__X__,X_X____X,________,
  __XXXXXX,X_XXXXXX,________,
  _____X__,__X____X,________,
  XXXXXXXX,XXX____X,________,
  _____X__,_X___XXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontMenuMSBlack24_CharInfo[28] = {
   {  18,  18,  3, acGUI_FontMenuMSBlack24_25B2 } /* code 25B2 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_25BC } /* code 25BC */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_505C } /* code 505C */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_52A8 } /* code 52A8 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_53CC } /* code 53CC */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_53D8 } /* code 53D8 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_53F3 } /* code 53F3 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_5411 } /* code 5411 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_5929 } /* code 5929 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_59CB } /* code 59CB */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_5DE6 } /* code 5DE6 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_5F00 } /* code 5F00 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_5F0F } /* code 5F0F */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_624B } /* code 624B */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_62C9 } /* code 62C9 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_673A } /* code 673A */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_6837 } /* code 6837 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_6A21 } /* code 6A21 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_6B62 } /* code 6B62 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_715C } /* code 715C */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_724C } /* code 724C */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_7535 } /* code 7535 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_81EA } /* code 81EA */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_8F6C } /* code 8F6C */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_901F } /* code 901F */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_91C7 } /* code 91C7 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_9525 } /* code 9525 */
  ,{  18,  18,  3, acGUI_FontMenuMSBlack24_9738 } /* code 9738 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop28 = {
   0x9738 /* first character */
  ,0x9738 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 27] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop27 = {
   0x9525 /* first character */
  ,0x9525 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 26] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop26 = {
   0x91C7 /* first character */
  ,0x91C7 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 25] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop25 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 24] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop24 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 23] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop23 = {
   0x81EA /* first character */
  ,0x81EA /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 22] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop22 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 21] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop21 = {
   0x724C /* first character */
  ,0x724C /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 20] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop20 = {
   0x715C /* first character */
  ,0x715C /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 19] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop19 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 18] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop18 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 17] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop17 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 16] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop16 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 15] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop15 = {
   0x62C9 /* first character */
  ,0x62C9 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 14] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop14 = {
   0x624B /* first character */
  ,0x624B /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 13] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop13 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 12] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop12 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 11] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop11 = {
   0x5DE6 /* first character */
  ,0x5DE6 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[ 10] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop10 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  9] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop9 = {
   0x5929 /* first character */
  ,0x5929 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  8] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop8 = {
   0x5411 /* first character */
  ,0x5411 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  7] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop7 = {
   0x53F3 /* first character */
  ,0x53F3 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  6] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop6 = {
   0x53D8 /* first character */
  ,0x53D8 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  5] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop5 = {
   0x53CC /* first character */
  ,0x53CC /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  4] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop4 = {
   0x52A8 /* first character */
  ,0x52A8 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  3] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop3 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  2] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop2 = {
   0x25BC /* first character */
  ,0x25BC /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  1] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontMenuMSBlack24_Prop1 = {
   0x25B2 /* first character */
  ,0x25B2 /* last character  */
  ,&GUI_FontMenuMSBlack24_CharInfo[  0] /* address of first character */
  ,&GUI_FontMenuMSBlack24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMenuMSBlack24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMenuMSBlack24_Prop1}
  ,19 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

