/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.28                          *
 *        Compiled Jan 30 2015, 16:41:06                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "motorcontrol.h"
/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_WINDOW_0 (GUI_ID_USER + 0x16)
#define ID_BUTTON_0 (GUI_ID_USER + 0x17)
#define ID_TEXT_0 (GUI_ID_USER + 0x18)
#define ID_SLIDER_0 (GUI_ID_USER + 0x19)
#define ID_BUTTON_1 (GUI_ID_USER + 0x1A)
#define ID_EDIT_0 (GUI_ID_USER + 0x1B)
#define ID_BUTTON_2 (GUI_ID_USER + 0x1C)
#define ID_BUTTON_3 (GUI_ID_USER + 0x1D)
#define ID_SLIDER_1 (GUI_ID_USER + 0x1E)
#define ID_TEXT_1 (GUI_ID_USER + 0x1F)
#define ID_BUTTON_4 (GUI_ID_USER + 0x20)
#define ID_BUTTON_5 (GUI_ID_USER + 0x21)
#define ID_EDIT_1 (GUI_ID_USER + 0x22)
#define ID_BUTTON_6 (GUI_ID_USER + 0x23)
#define ID_EDIT_2 (GUI_ID_USER + 0x25)
#define ID_TEXT_2 (GUI_ID_USER + 0x26)
#define ID_TEXT_3 (GUI_ID_USER + 0x27)
#define ID_TEXT_4 (GUI_ID_USER + 0x28)
#define ID_EDIT_3 (GUI_ID_USER + 0x29)
#define ID_EDIT_4 (GUI_ID_USER + 0x2A)

#define FontMenuSong24 &GUI_FontMenuSong24
#define FontMenuMSBlack24 &GUI_FontMenuMSBlack24

#define RIGHT_MOTOR 1
#define LEFT_MOTOR  0
/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

extern GUI_CONST_STORAGE GUI_FONT GUI_FontMenuSong24;
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMenuMSBlack24;

extern GUI_HWIN DualMotorWIN;
extern WM_HWIN EditLeftRealSpeed;
extern WM_HWIN EditRightRealSpeed;
extern WM_HWIN SliderDualItem;
extern GUI_HWIN StartItem;

WM_HWIN SingleMotorWIN;
WM_HWIN SingleEditLeftRealSpeed;
WM_HWIN SingleEditRightRealSpeed;
WM_HWIN SliderLeftItem;
WM_HWIN SliderRightItem;
WM_HWIN SingleEditLeftSetSpeed;
WM_HWIN SingleEditRightSetSpeed;

GUI_HWIN LeftStopItem;
GUI_HWIN RightStopItem;

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "single_motor", ID_WINDOW_0, 5, 45, 470, 675, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "ChangeMode", ID_BUTTON_0, 185, 600, 100, 60, 0, 0x0, 0},
    {TEXT_CreateIndirect, "L_Motor", ID_TEXT_0, 10, 165, 80, 40, 0, 0x0, 0},
    {SLIDER_CreateIndirect, "LSlider", ID_SLIDER_0, 100, 155, 250, 70, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "LUP", ID_BUTTON_1, 370, 115, 80, 40, 0, 0x0, 0},
    {EDIT_CreateIndirect, "LSpeed", ID_EDIT_0, 370, 165, 80, 40, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "LDown", ID_BUTTON_2, 370, 215, 80, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "LStop", ID_BUTTON_3, 190, 90, 80, 40, 0, 0x0, 0},
    {SLIDER_CreateIndirect, "RSlider", ID_SLIDER_1, 100, 350, 250, 70, 0, 0x0, 0},
    {TEXT_CreateIndirect, "R_Motor", ID_TEXT_1, 10, 360, 80, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "RUP", ID_BUTTON_4, 370, 310, 80, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "RDown", ID_BUTTON_5, 370, 410, 80, 40, 0, 0x0, 0},
    {EDIT_CreateIndirect, "RSpeed", ID_EDIT_1, 370, 360, 80, 40, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "RStop", ID_BUTTON_6, 190, 285, 80, 40, 0, 0x0, 0},
    {EDIT_CreateIndirect, "SampleEdit", ID_EDIT_2, 195, 545, 80, 40, 0, 0x64, 0},
    {TEXT_CreateIndirect, "SampleData:", ID_TEXT_2, 110, 545, 80, 40, 0, 0x64, 0},
    // USER START (Optionally insert additional widgets)
    {TEXT_CreateIndirect, "LeftRealSpeed", ID_TEXT_3, 105, 440, 80, 40, 0, 0x64, 0},
    {TEXT_CreateIndirect, "RightRealSpeed", ID_TEXT_4, 285, 440, 80, 40, 0, 0x64, 0},
    {EDIT_CreateIndirect, "LRsp", ID_EDIT_3, 105, 485, 80, 40, 0, 0x64, 0},
    {EDIT_CreateIndirect, "RRsp", ID_EDIT_4, 285, 485, 80, 40, 0, 0x64, 0},
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */
// TODO extern WM_HWIN PageItem;

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  WM_HWIN editItem;
  int v;
  char str[6];
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'LSlider'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SliderLeftItem = hItem;
    SLIDER_SetRange(hItem, 500, 5000);
    SLIDER_SetValue(hItem, 500);
    //
    // Initialization of 'RSlider'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
    SliderRightItem = hItem;
    SLIDER_SetRange(hItem, 500, 5000);
    SLIDER_SetValue(hItem, 500);
    //
    // Initialization of 'ChangeMode'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, FontMenuMSBlack24);
    BUTTON_SetText(hItem, "模式");
    //
    // Initialization of 'L_Motor'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, FontMenuMSBlack24);
    TEXT_SetText(hItem, "左电机");
    //
    // Initialization of 'LUP'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, FontMenuSong24);
    BUTTON_SetText(hItem, "▲");
    //
    // Initialization of 'LSpeed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    SingleEditLeftSetSpeed = hItem;
    EDIT_SetText(hItem, "500");
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'LDown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, FontMenuSong24);
    BUTTON_SetText(hItem, "▼");
    //
    // Initialization of 'LStop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    LeftStopItem = hItem;
    BUTTON_SetFont(hItem, FontMenuMSBlack24);
    if (MotorConfig.real_left_speed)
    {
      BUTTON_SetText(hItem, "左停止");
    }
    else
    {
      BUTTON_SetText(hItem, "左开始");
    }

    //
    // Initialization of 'R_Motor'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, FontMenuMSBlack24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "右电机");
    //
    // Initialization of 'RUP'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, FontMenuSong24);
    BUTTON_SetText(hItem, "▲");
    //
    // Initialization of 'RDown'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, FontMenuSong24);
    BUTTON_SetText(hItem, "▼");
    //
    // Initialization of 'RSpeed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    SingleEditRightSetSpeed = hItem;
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetText(hItem, "500");
    //
    // Initialization of 'RStop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    RightStopItem = hItem;
    BUTTON_SetFont(hItem, FontMenuMSBlack24);
    if (MotorConfig.real_right_speed)
    {
      BUTTON_SetText(hItem, "右停止");
    }
    else
    {
      BUTTON_SetText(hItem, "右开始");
    }

    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetFont(hItem, FontMenuMSBlack24);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetText(hItem, "霸");
    //
    // Initialization of 'SampleData:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, FontMenuMSBlack24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "采样");
    //! USER START (Optionally insert additional code for further widget initialization)
    //
    // Initialization of 'LeftRealSpeed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, FontMenuMSBlack24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "左转速");
    //
    // Initialization of 'RightRealSpeed'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetFont(hItem, FontMenuMSBlack24);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "右转速");
    //
    // Initialization of 'LRSp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    SingleEditLeftRealSpeed = hItem;
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetText(hItem, "0");
    //
    // Initialization of 'RRSp'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    SingleEditRightRealSpeed = hItem;
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetText(hItem, "0");
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_BUTTON_0: // Notifications sent by 'ChangeMode'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
      {
        //! Change the manual control page between Dual/Single Motor

        // MULTIPAGE_AttachWindow(PageItem, 0, Createdual_motor());
        //TODO modemode stop
        MotorConfig.mode = 0;
        if (MotorConfig.real_left_speed)
        {
          EDIT_SetText(EditLeftRealSpeed, Int2String(-MotorConfig.real_left_speed + 5500, str));
        }
        else 
        {
          EDIT_SetText(EditLeftRealSpeed, "0");
        }

        if (MotorConfig.real_right_speed)
        {
          EDIT_SetText(EditRightRealSpeed, Int2String(-MotorConfig.real_right_speed + 5500, str));
        }
        else 
        {
          EDIT_SetText(EditRightRealSpeed, "0");
        }

        // Restore the two set_speed when switch to Dual Control Mode from Single Control Mode
        v = SLIDER_GetValue(SliderDualItem);
        MotorConfig.set_left_speed = (u16)(-v + 5500);
        MotorConfig.set_right_speed = (u16)(-v + 5500);
        
        WM_ShowWindow(DualMotorWIN);
        WM_HideWindow(SingleMotorWIN);
        // WM_DeleteWindow(SingleMotorWIN);
      }
      break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'LSlider'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // TODO 先做清楚启动/停止的逻辑关系！
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        v = SLIDER_GetValue(hItem);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        EDIT_SetText(hItem, Int2String(v, str));
        //TODO mode无用了？
        ChangeSpecificSpeed(&MotorConfig, (u16)v, LEFT_MOTOR);
        if (MotorConfig.real_left_speed)
        {
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
          EDIT_SetText(hItem, Int2String(v, str));
        } 
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'LUP'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        editItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        if (MotorConfig.set_left_speed - 100 > 500)
        {
          EDIT_GetText(editItem, str, 5);
          v = String2Int(str);
          ChangeSpecificSpeed(&MotorConfig, (u16)v + 100, LEFT_MOTOR);
          EDIT_SetText(editItem, Int2String(v + 100, str));
          SLIDER_SetValue(hItem, v + 100);
          if (MotorConfig.real_left_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
            EDIT_SetText(hItem, Int2String(v + 100, str));
          }
          
        }
        else
        {
          ChangeSpecificSpeed(&MotorConfig, 5000, LEFT_MOTOR);
          EDIT_SetText(editItem, "5000");
          SLIDER_SetValue(hItem, 5000);
          if (MotorConfig.real_left_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
            EDIT_SetText(hItem, "5000");
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'LSpeed'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'LDown'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
        editItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        if (MotorConfig.set_left_speed + 100 < 5000)
        {
          EDIT_GetText(editItem, str, 5);
          v = String2Int(str);
          ChangeSpecificSpeed(&MotorConfig, (u16)v - 100, LEFT_MOTOR);
          EDIT_SetText(editItem, Int2String(v - 100, str));
          SLIDER_SetValue(hItem, v - 100);
          if (MotorConfig.real_left_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
            EDIT_SetText(hItem, Int2String(v - 100, str));
          }
          
        }
        else
        {
          ChangeSpecificSpeed(&MotorConfig, 500, LEFT_MOTOR);
          EDIT_SetText(editItem, "500");
          SLIDER_SetValue(hItem, 500);
          if (MotorConfig.real_left_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
            EDIT_SetText(hItem, "500");
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'LStop'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        if (MotorConfig.real_left_speed)
        {
          //MotorConfig.real_left_speed = 0;
          StopSpecificMotor(&MotorConfig, 0);
          BUTTON_SetText(hItem, "左开始");
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
          EDIT_SetText(hItem, "0");
        }
        else
        {
          //MotorConfig.real_left_speed = MotorConfig.set_left_speed;
          StartSpecificMotor(&MotorConfig, 0);
          BUTTON_SetText(hItem, "左停止");
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
          EDIT_SetText(hItem, Int2String(-MotorConfig.real_left_speed+5500, str));
        }

        // Update the Start button
        if (MotorConfig.real_left_speed || MotorConfig.real_right_speed)
        {
          MotorConfig.enable = 1;
          BUTTON_SetText(StartItem, "停止");
        }
        else
        {
          MotorConfig.enable = 0;
          BUTTON_SetText(StartItem, "开始");
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_SLIDER_1: // Notifications sent by 'RSlider'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
        v = SLIDER_GetValue(hItem);
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
        EDIT_SetText(hItem, Int2String(v, str));
        //TODO mode无用了？
        ChangeSpecificSpeed(&MotorConfig, (u16)v, RIGHT_MOTOR);
        if (MotorConfig.real_right_speed)
        {
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
          EDIT_SetText(hItem, Int2String(v, str));
        }         
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'RUP'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
        editItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
        if (MotorConfig.set_right_speed - 100 > 500)
        {
          EDIT_GetText(editItem, str, 5);
          v = String2Int(str);
          ChangeSpecificSpeed(&MotorConfig, (u16)v + 100, RIGHT_MOTOR);
          EDIT_SetText(editItem, Int2String(v + 100, str));
          SLIDER_SetValue(hItem, v + 100);
          if (MotorConfig.real_right_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
            EDIT_SetText(hItem, Int2String(v + 100, str));
          }
          
        }
        else
        {
          ChangeSpecificSpeed(&MotorConfig, 5000, RIGHT_MOTOR);
          EDIT_SetText(editItem, "5000");
          SLIDER_SetValue(hItem, 5000);
          if (MotorConfig.real_right_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
            EDIT_SetText(hItem, "5000");
          }
        }
        

        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'RDown'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
        editItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
        if (MotorConfig.set_right_speed + 100 < 5000)
        {
          EDIT_GetText(editItem, str, 5);
          v = String2Int(str);
          ChangeSpecificSpeed(&MotorConfig, (u16)v - 100, RIGHT_MOTOR);
          EDIT_SetText(editItem, Int2String(v - 100, str));
          SLIDER_SetValue(hItem, v - 100);
          if (MotorConfig.real_right_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
            EDIT_SetText(hItem, Int2String(v - 100, str));
          }
          
        }
        else
        {
          ChangeSpecificSpeed(&MotorConfig, 500, RIGHT_MOTOR);
          EDIT_SetText(editItem, "500");
          SLIDER_SetValue(hItem, 500);
          if (MotorConfig.real_right_speed)
          {
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
            EDIT_SetText(hItem, "500");
          }
        }

        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'RSpeed'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'RStop'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
        if (MotorConfig.real_right_speed)
        {
          //MotorConfig.real_right_speed = 0;
          StopSpecificMotor(&MotorConfig, 1);
          BUTTON_SetText(hItem, "右开始");
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
          EDIT_SetText(hItem, "0");
        }
        else
        {
          //MotorConfig.real_right_speed = MotorConfig.set_right_speed;
          StartSpecificMotor(&MotorConfig, 1);
          BUTTON_SetText(hItem, "右停止");
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
          EDIT_SetText(hItem, Int2String(-MotorConfig.real_right_speed+5500, str));
        }

        // Update the Start button
        if (MotorConfig.real_left_speed || MotorConfig.real_right_speed)
        {
          MotorConfig.enable = 1;
          BUTTON_SetText(StartItem, "停止");
        }
        else
        {
          MotorConfig.enable = 0;
          BUTTON_SetText(StartItem, "开始");
        }

        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'SampleEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       Createsingle_motor
 */
WM_HWIN Createsingle_motor(void);
WM_HWIN Createsingle_motor(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  SingleMotorWIN = hWin;
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
