/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.28                          *
 *        Compiled Jan 30 2015, 16:41:06                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include "FTM_FrameDLG.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_BUTTON_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_1 (GUI_ID_USER + 0x05)
#define ID_BUTTON_2 (GUI_ID_USER + 0x06)
#define ID_EDIT_0 (GUI_ID_USER + 0x07)
#define ID_EDIT_1 (GUI_ID_USER + 0x08)
#define ID_BUTTON_3 (GUI_ID_USER + 0x09)
#define ID_EDIT_2 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0B)
#define ID_TEXT_0 (GUI_ID_USER + 0x0C)
#define ID_TEXT_1 (GUI_ID_USER + 0x0D)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Global data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)

// DualCtrl Window Items

// 双电机控制窗口文件里的Edit控件句柄数组，分别对应：
// 0:实际左转速; 1:实际右转速； 2：预设双电机转速
GUI_HWIN _aDualEdit[3];
// 双电机控制窗口文件里的按钮控件句柄数组，分别对应：
// 0:开始按钮; 1:方向按钮
GUI_HWIN _aDualButton[2];
// 双电机滑块
GUI_HWIN DualSlider;

// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "DualCtrl_Win", ID_WINDOW_0, 0, 0, 470, 360, 0, 0x0, 0},
    {SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 60, 65, 300, 60, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "StartBtn", ID_BUTTON_0, 70, 295, 80, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "ModeBtn", ID_BUTTON_1, 190, 295, 80, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "DirBtn", ID_BUTTON_2, 315, 295, 80, 40, 0, 0x0, 0},
    {EDIT_CreateIndirect, "RLspEdit", ID_EDIT_0, 115, 200, 80, 40, 0, 0x64, 0},
    {EDIT_CreateIndirect, "RRspEdit", ID_EDIT_1, 260, 200, 80, 40, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "UpBtn", ID_BUTTON_3, 375, 25, 70, 40, 0, 0x0, 0},
    {EDIT_CreateIndirect, "SSpEdit", ID_EDIT_2, 375, 75, 70, 40, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "DownBtn", ID_BUTTON_4, 375, 125, 70, 40, 0, 0x0, 0},
    {TEXT_CreateIndirect, "LspText", ID_TEXT_0, 115, 160, 80, 40, 0, 0x0, 0},
    {TEXT_CreateIndirect, "RspText", ID_TEXT_1, 260, 160, 80, 40, 0, 0x0, 0},
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  char str[6];
  int value;
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Slider'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetRange(hItem, 500, 5000);
    SLIDER_SetValue(hItem, 500);
    DualSlider = hItem;
    //
    // Initialization of 'StartBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "开始");
    _aDualButton[DualStartBtn] = hItem;
    //
    // Initialization of 'ModeBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "模式");
    //
    // Initialization of 'DirBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "靠近中心");
    _aDualButton[DirBtn] = hItem;
    //
    // Initialization of 'RLspEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "0");
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    _aDualEdit[REAL_LEFT_SPEED] = hItem;
    //
    // Initialization of 'RRspEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    _aDualEdit[REAL_RIGHT_SPEED] = hItem;
    //
    // Initialization of 'UpBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "▲");
    //
    // Initialization of 'SSpEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "500");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    _aDualEdit[SET_DUAL_SPEED] = hItem;
    //
    // Initialization of 'DownBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "▼");
    //
    // Initialization of 'LspText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontMSBlack24);
    TEXT_SetText(hItem, "左转速");
    //
    // Initialization of 'RspText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontMSBlack24);
    TEXT_SetText(hItem, "右转速");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        value = SLIDER_GetValue(DualSlider);
        EDIT_SetText(_aDualEdit[SET_DUAL_SPEED], Int2String(value, str));
        ChangeSpecificSpeed((u16)value, LEFT_MOTOR);
        ChangeSpecificSpeed((u16)value, RIGHT_MOTOR);
        //! If there is only one motor operating when on the dual motors control page,
        //! the slider will only be effective to the operating motor.
        //! You can tap "Stop" button to stop and tap it again to boot both motors,
        //! and then the slider is effective to both motors.
        if (GetMotorConfig(REAL_LEFT_SPEED))
        {
          EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], Int2String(value, str));
        }
        if (GetMotorConfig(REAL_RIGHT_SPEED))
        {
          EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], Int2String(value, str));
        }

        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'StartBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        {
          hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
          if (GetMotorConfig(REAL_LEFT_SPEED) || GetMotorConfig(REAL_RIGHT_SPEED))
          {

            BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
            BUTTON_SetText(hItem, "开始");
            BUTTON_SetText(_aSingleButton[DualStartBtn], "开始");

            if (GetMotorConfig(REAL_LEFT_SPEED)) // If the left motor is operating
            {
              StopSpecificMotor(LEFT_MOTOR);
              BUTTON_SetText(_aSingleButton[LStartBtn], "左开始");
              EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], "0");
              EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], "0");
            }
            if (GetMotorConfig(REAL_RIGHT_SPEED)) // If the right motor is operating
            {
              StopSpecificMotor(RIGHT_MOTOR);
              BUTTON_SetText(_aSingleButton[RStartBtn], "右开始");
              EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], "0");
              EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], "0");
            }
          }
          else
          {
            BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
            BUTTON_SetText(hItem, "停止");
            BUTTON_SetText(_aSingleButton[DualStartBtn], "停止");
            if (!GetMotorConfig(REAL_LEFT_SPEED)) // If the left motor is not operating
            {
              StartSpecificMotor(LEFT_MOTOR);
              EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], Int2String((int)(-GetMotorConfig(REAL_LEFT_SPEED) + 5500), str));
            }

            if (!GetMotorConfig(REAL_RIGHT_SPEED)) // If the right motor is not operating
            {
              StartSpecificMotor(RIGHT_MOTOR);
              EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], Int2String((int)(-GetMotorConfig(REAL_RIGHT_SPEED) + 5500), str));
            }
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'ModeBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_HideWindow(DualCtrl_Win);
        WM_ShowWindow(SingCtrl_Win);

        if (GetMotorConfig(REAL_LEFT_SPEED))
        {
          EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], Int2String(-GetMotorConfig(REAL_LEFT_SPEED) + 5500, str));
          BUTTON_SetText(_aSingleButton[LStartBtn], "左停止");
        }
        else
        {
          EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], "0");
          BUTTON_SetText(_aSingleButton[LStartBtn], "左开始");
        }

        if (GetMotorConfig(REAL_RIGHT_SPEED))
        {
          EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], Int2String(-GetMotorConfig(REAL_RIGHT_SPEED) + 5500, str));
          BUTTON_SetText(_aSingleButton[RStartBtn], "右停止");
        }
        else
        {
          EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], "0");
          BUTTON_SetText(_aSingleButton[RStartBtn], "右开始");
        }

        // Synchronize the set values in single motor mode if motors are running under dual motor mode
        // So user can adjust the speed of each motor independently based on current realtime speed
        if (GetMotorConfig(REAL_LEFT_SPEED) == GetMotorConfig(REAL_RIGHT_SPEED) 
          && GetMotorConfig(SET_LEFT_SPEED) == GetMotorConfig(REAL_LEFT_SPEED) 
          && GetMotorConfig(SET_RIGHT_SPEED) == GetMotorConfig(REAL_RIGHT_SPEED))
        {
          value = SLIDER_GetValue(DualSlider);
          SLIDER_SetValue(_aSingleSlider[SINGLE_LEFT_SLIDER], value);
          SLIDER_SetValue(_aSingleSlider[SINGLE_RIGHT_SLIDER], value);
          EDIT_SetText(_aSingleEdit[SET_LEFT_SPEED], Int2String(value, str));
          EDIT_SetText(_aSingleEdit[SET_RIGHT_SPEED], Int2String(value, str));
        }
 
        value = SLIDER_GetValue(_aSingleSlider[SINGLE_LEFT_SLIDER]);
        SetMotorConfig(SET_LEFT_SPEED, -value + 5500);
        value = SLIDER_GetValue(_aSingleSlider[SINGLE_RIGHT_SLIDER]);
        SetMotorConfig(SET_RIGHT_SPEED, -value + 5500);
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'DirBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)

        ChangeDirection();
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
        if (GetMotorConfig(DIRECTION))
        {
          BUTTON_SetText(_aDualButton[DirBtn], "两侧拉伸");
          BUTTON_SetText(_aSingleButton[DirBtn], "两侧拉伸");
        }
        else
        {
          BUTTON_SetText(_aDualButton[DirBtn], "靠近中心");
          BUTTON_SetText(_aSingleButton[DirBtn], "靠近中心");
        }

        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'RLspEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'RRspEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'UpBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if (GetMotorConfig(SET_RIGHT_SPEED) - 100 > 500 && GetMotorConfig(SET_LEFT_SPEED) - 100 > 500)
        {
          EDIT_GetText(_aDualEdit[SET_DUAL_SPEED], str, 5);
          value = String2Int(str);
          ChangeSpecificSpeed((u16)value + 100, LEFT_MOTOR);
          ChangeSpecificSpeed((u16)value + 100, RIGHT_MOTOR);
          EDIT_SetText(_aDualEdit[SET_DUAL_SPEED], Int2String(value + 100, str));
          SLIDER_SetValue(DualSlider, value + 100);

          //! If there is only one motor operating when on the dual motors control page,
          //! the button will only be effective to the operating motor.
          //! You can tap "Stop" button to stop and tap it again to boot both motors,
          //! and then the slider is effective to both motors.
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], Int2String(value + 100, str));
          }
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], Int2String(value + 100, str));
          }
        }
        else
        {
          // Set to maximum speed if the upper limit is reached
          ChangeSpecificSpeed(5000, LEFT_MOTOR);
          ChangeSpecificSpeed(5000, RIGHT_MOTOR);
          EDIT_SetText(_aDualEdit[SET_DUAL_SPEED], "5000");
          SLIDER_SetValue(DualSlider, 5000);

          //! If there is only one motor operating when on the dual motors control page,
          //! the button will only be effective to the operating motor.
          //! You can tap "Stop" button to stop and tap it again to boot both motors,
          //! and then the slider is effective to both motors.
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], "5000");
          }
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], "5000");
          }
        }

        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'SSpEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'DownBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if (GetMotorConfig(SET_RIGHT_SPEED) + 100 < 5000 && GetMotorConfig(SET_LEFT_SPEED) + 100 < 5000)
        {
          EDIT_GetText(_aDualEdit[SET_DUAL_SPEED], str, 5);
          value = String2Int(str);

          ChangeSpecificSpeed((u16)value - 100, LEFT_MOTOR);
          ChangeSpecificSpeed((u16)value - 100, RIGHT_MOTOR);
          EDIT_SetText(_aDualEdit[SET_DUAL_SPEED], Int2String(value - 100, str));
          SLIDER_SetValue(DualSlider, value - 100);

          //! If there is only one motor operating when on the dual motors control page,
          //! the button will only be effective to the operating motor.
          //! You can tap "Stop" button to stop and tap it again to boot both motors,
          //! and then the slider is effective to both motors.
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], Int2String(value - 100, str));
          }
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], Int2String(value - 100, str));
          }
        }
        else
        {
          // Set to maximum speed if the upper limit is reached
          ChangeSpecificSpeed(500, LEFT_MOTOR);
          ChangeSpecificSpeed(500, RIGHT_MOTOR);
          EDIT_SetText(_aDualEdit[SET_DUAL_SPEED], "500");
          SLIDER_SetValue(DualSlider, 500);

          //! If there is only one motor operating when on the dual motors control page,
          //! the button will only be effective to the operating motor.
          //! You can tap "Stop" button to stop and tap it again to boot both motors,
          //! and then the slider is effective to both motors.
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], "500");
          }
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], "500");
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateDualCtrl_Win
 */
WM_HWIN CreateDualCtrl_Win(void);
WM_HWIN CreateDualCtrl_Win(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
