/*********************************************************************
 *                                                                    *
 *                SEGGER Microcontroller GmbH & Co. KG                *
 *        Solutions for real time microcontroller applications        *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 * C-file generated by:                                               *
 *                                                                    *
 *        GUI_Builder for emWin version 5.28                          *
 *        Compiled Jan 30 2015, 16:41:06                              *
 *        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
 *                                                                    *
 **********************************************************************
 *                                                                    *
 *        Internet: www.segger.com  Support: support@segger.com       *
 *                                                                    *
 **********************************************************************
 */

// USER START (Optionally insert additional includes)
#include "FTM_FrameDLG.h"
// USER END

#include "DIALOG.h"
/*********************************************************************
 *
 *       Defines
 *
 **********************************************************************
 */
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_SLIDER_0 (GUI_ID_USER + 0x01)
#define ID_SLIDER_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_BUTTON_0 (GUI_ID_USER + 0x05)
#define ID_EDIT_0 (GUI_ID_USER + 0x06)
#define ID_BUTTON_1 (GUI_ID_USER + 0x07)
#define ID_EDIT_1 (GUI_ID_USER + 0x08)
#define ID_BUTTON_2 (GUI_ID_USER + 0x09)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0B)
#define ID_EDIT_2 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_5 (GUI_ID_USER + 0x0D)
#define ID_EDIT_3 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_6 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_7 (GUI_ID_USER + 0x10)
#define ID_BUTTON_8 (GUI_ID_USER + 0x11)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
 *
 *       Static data
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static data)

// 单电机控制窗口文件里的按钮控件句柄数组，分别对应：
// 0:开始按钮; 1:方向按钮； 2：左开始按钮 3：右开始按钮
GUI_HWIN _aSingleButton[4];

// 单电机控制窗口文件里的Edit控件句柄数组，分别对应：
// 0:实际左转速; 1:实际右转速； 2：预设左转速 3：预设右转速
GUI_HWIN _aSingleEdit[4];

// 单电机控制窗口文件里的Slider控件句柄数组，分别对应：
// 0:左电机转速Slider; 1:右电机转速Slider；
GUI_HWIN _aSingleSlider[2];

// USER END

/*********************************************************************
 *
 *       _aDialogCreate
 */
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    {WINDOW_CreateIndirect, "SingCtrl_Win", ID_WINDOW_0, 0, 0, 470, 360, 0, 0x0, 0},
    {SLIDER_CreateIndirect, "LeftSlider", ID_SLIDER_0, 60, 40, 300, 50, 0, 0x0, 0},
    {SLIDER_CreateIndirect, "RightSlider", ID_SLIDER_1, 60, 170, 300, 50, 0, 0x0, 0},
    {TEXT_CreateIndirect, "LeftText", ID_TEXT_0, 2, 53, 60, 25, 0, 0x64, 0},
    {TEXT_CreateIndirect, "RightText", ID_TEXT_1, 2, 183, 60, 25, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "LupBtn", ID_BUTTON_0, 375, 10, 70, 30, 0, 0x0, 0},
    {EDIT_CreateIndirect, "SLspEdit", ID_EDIT_0, 375, 45, 70, 30, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "LdnBtn", ID_BUTTON_1, 375, 80, 70, 30, 0, 0x0, 0},
    {EDIT_CreateIndirect, "RLspEdit", ID_EDIT_1, 255, 105, 70, 30, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "LStartBtn", ID_BUTTON_2, 130, 105, 80, 30, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "RupBtn", ID_BUTTON_3, 375, 140, 70, 30, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "RStartBtn", ID_BUTTON_4, 130, 235, 80, 30, 0, 0x0, 0},
    {EDIT_CreateIndirect, "RRspEdit", ID_EDIT_2, 260, 235, 70, 30, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "RdnBtn", ID_BUTTON_5, 375, 210, 70, 30, 0, 0x0, 0},
    {EDIT_CreateIndirect, "SRspEdit", ID_EDIT_3, 375, 175, 70, 30, 0, 0x64, 0},
    {BUTTON_CreateIndirect, "DualStartBtn", ID_BUTTON_6, 70, 295, 80, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "ModeBtn", ID_BUTTON_7, 190, 295, 80, 40, 0, 0x0, 0},
    {BUTTON_CreateIndirect, "DirBtn", ID_BUTTON_8, 315, 295, 80, 40, 0, 0x0, 0},
    // USER START (Optionally insert additional widgets)
    // USER END
};

/*********************************************************************
 *
 *       Static code
 *
 **********************************************************************
 */

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
 *
 *       _cbDialog
 */
static void _cbDialog(WM_MESSAGE *pMsg)
{
  WM_HWIN hItem;
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
  char str[6];
  int value;
  // USER END

  switch (pMsg->MsgId)
  {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'LeftSlider'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
    SLIDER_SetRange(hItem, 500, 5000);
    SLIDER_SetValue(hItem, 500);
    _aSingleSlider[SINGLE_LEFT_SLIDER] = hItem;
    //
    // Initialization of 'RightSlider'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
    SLIDER_SetRange(hItem, 500, 5000);
    SLIDER_SetValue(hItem, 500);
    _aSingleSlider[SINGLE_RIGHT_SLIDER] = hItem;
    //
    // Initialization of 'LeftText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontMSBlack24);
    TEXT_SetText(hItem, "左转速");
    //
    // Initialization of 'RightText'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, &GUI_FontMSBlack24);
    TEXT_SetText(hItem, "右转速");
    //
    // Initialization of 'LupBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "▲");
    //
    // Initialization of 'SLspEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "500");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    _aSingleEdit[SET_LEFT_SPEED] = hItem;
    //
    // Initialization of 'LdnBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "▼");
    //
    // Initialization of 'RLspEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    _aSingleEdit[REAL_LEFT_SPEED] = hItem;
    //
    // Initialization of 'LStartBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "左开始");
    _aSingleButton[LStartBtn] = hItem;
    //
    // Initialization of 'RupBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "▲");
    //
    // Initialization of 'RStartBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "右开始");
    _aSingleButton[RStartBtn] = hItem;
    //
    // Initialization of 'RRspEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "0");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    _aSingleEdit[REAL_RIGHT_SPEED] = hItem;
    //
    // Initialization of 'RdnBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "▼");
    //
    // Initialization of 'SRspEdit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "500");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    EDIT_SetFont(hItem, GUI_FONT_16_ASCII);
    _aSingleEdit[SET_RIGHT_SPEED] = hItem;
    //
    // Initialization of 'DualStartBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "开始");
    _aSingleButton[DualStartBtn] = hItem;
    //
    // Initialization of 'ModeBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "模式");
    //
    // Initialization of 'DirBtn'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
    BUTTON_SetText(hItem, "靠近中心");
    _aSingleButton[DirBtn] = hItem;
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch (Id)
    {
    case ID_SLIDER_0: // Notifications sent by 'LeftSlider'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        value = SLIDER_GetValue(_aSingleSlider[SINGLE_LEFT_SLIDER]);
        EDIT_SetText(_aSingleEdit[SET_LEFT_SPEED], Int2String(value, str));
        ChangeSpecificSpeed((u16)value, LEFT_MOTOR);
        if (GetMotorConfig(REAL_LEFT_SPEED))
        {
          EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], Int2String(value, str));
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_SLIDER_1: // Notifications sent by 'RightSlider'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        value = SLIDER_GetValue(_aSingleSlider[SINGLE_RIGHT_SLIDER]);
        EDIT_SetText(_aSingleEdit[SET_RIGHT_SPEED], Int2String(value, str));
        ChangeSpecificSpeed((u16)value, RIGHT_MOTOR);
        if (GetMotorConfig(REAL_RIGHT_SPEED))
        {
          EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], Int2String(value, str));
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'LupBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if (GetMotorConfig(SET_LEFT_SPEED) - 100 > 500)
        {
          EDIT_GetText(_aSingleEdit[SET_LEFT_SPEED], str, 5);
          value = String2Int(str);
          ChangeSpecificSpeed((u16)value - 100, LEFT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_LEFT_SPEED], Int2String(value + 100, str));
          SLIDER_SetValue(_aSingleSlider[SINGLE_LEFT_SLIDER], value + 100);
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], Int2String(value + 100, str));
          }
        }
        else
        {
          ChangeSpecificSpeed(5000, LEFT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_LEFT_SPEED], "5000");
          SLIDER_SetValue(_aSingleSlider[SINGLE_LEFT_SLIDER], 5000);
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], "5000");
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'SLspEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'LdnBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if (GetMotorConfig(SET_LEFT_SPEED) + 100 < 5000)
        {
          EDIT_GetText(_aSingleEdit[SET_LEFT_SPEED], str, 5);
          value = String2Int(str);
          ChangeSpecificSpeed((u16)value - 100, LEFT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_LEFT_SPEED], Int2String(value - 100, str));
          SLIDER_SetValue(_aSingleSlider[SINGLE_LEFT_SLIDER], value - 100);
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], Int2String(value - 100, str));
          }
        }
        else
        {
          ChangeSpecificSpeed(500, LEFT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_LEFT_SPEED], "500");
          SLIDER_SetValue(_aSingleSlider[SINGLE_LEFT_SLIDER], 500);
          if (GetMotorConfig(REAL_LEFT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], "500");
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'RLspEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'LStartBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        if (GetMotorConfig(REAL_LEFT_SPEED))
        {
          StopSpecificMotor(LEFT_MOTOR);
          BUTTON_SetText(hItem, "左开始");
          EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], "0");
        }
        else
        {
          StartSpecificMotor(LEFT_MOTOR);
          BUTTON_SetText(hItem, "左停止");
          hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
          EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], Int2String(-GetMotorConfig(REAL_LEFT_SPEED) + 5500, str));
        }

        // Update the StartBtn in SingleCtrl window
        if (GetMotorConfig(REAL_LEFT_SPEED) || GetMotorConfig(REAL_RIGHT_SPEED))
        {
          BUTTON_SetText(_aSingleButton[DualStartBtn], "停止");
        }
        else
        {
          BUTTON_SetText(_aSingleButton[DualStartBtn], "开始");
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'RupBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if (GetMotorConfig(SET_RIGHT_SPEED) - 100 > 500)
        {
          EDIT_GetText(_aSingleEdit[SET_RIGHT_SPEED], str, 5);
          value = String2Int(str);
          ChangeSpecificSpeed((u16)value - 100, RIGHT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_RIGHT_SPEED], Int2String(value + 100, str));
          SLIDER_SetValue(_aSingleSlider[SINGLE_RIGHT_SLIDER], value + 100);
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], Int2String(value + 100, str));
          }
        }
        else
        {
          ChangeSpecificSpeed(5000, RIGHT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_RIGHT_SPEED], "5000");
          SLIDER_SetValue(_aSingleSlider[SINGLE_RIGHT_SLIDER], 5000);
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], "5000");
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'RStartBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        if (GetMotorConfig(REAL_RIGHT_SPEED))
        {
          StopSpecificMotor(RIGHT_MOTOR);
          BUTTON_SetText(hItem, "右开始");
          EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], "0");
        }
        else
        {
          StartSpecificMotor(RIGHT_MOTOR);
          BUTTON_SetText(hItem, "右停止");
          EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], Int2String(-GetMotorConfig(REAL_RIGHT_SPEED) + 5500, str));
        }

        // Update the StartBtn SingleCtrl window
        if (GetMotorConfig(REAL_LEFT_SPEED) || GetMotorConfig(REAL_RIGHT_SPEED))
        {
          BUTTON_SetText(_aSingleButton[DualStartBtn], "停止");
        }
        else
        {
          BUTTON_SetText(_aSingleButton[DualStartBtn], "开始");
        }

        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'RRspEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'RdnBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        if (GetMotorConfig(SET_RIGHT_SPEED) + 100 < 5000)
        {
          EDIT_GetText(_aSingleEdit[SET_RIGHT_SPEED], str, 5);
          value = String2Int(str);
          ChangeSpecificSpeed((u16)value - 100, RIGHT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_RIGHT_SPEED], Int2String(value - 100, str));
          SLIDER_SetValue(_aSingleSlider[SINGLE_RIGHT_SLIDER], value - 100);
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], Int2String(value - 100, str));
          }
        }
        else
        {
          ChangeSpecificSpeed(500, RIGHT_MOTOR);
          EDIT_SetText(_aSingleEdit[SET_RIGHT_SPEED], "500");
          SLIDER_SetValue(_aSingleSlider[SINGLE_RIGHT_SLIDER], 500);
          if (GetMotorConfig(REAL_RIGHT_SPEED))
          {
            EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], "500");
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'SRspEdit'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'DualStartBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        {

          hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
          if (GetMotorConfig(REAL_LEFT_SPEED) || GetMotorConfig(REAL_RIGHT_SPEED))
          {

            BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
            BUTTON_SetText(hItem, "开始");

            if (GetMotorConfig(REAL_LEFT_SPEED)) // If the left motor is operating
            {
              StopSpecificMotor(LEFT_MOTOR);
              BUTTON_SetText(_aSingleButton[LStartBtn], "左开始");
              EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], "0");
            }
            if (GetMotorConfig(REAL_RIGHT_SPEED)) // If the right motor is operating
            {
              StopSpecificMotor(RIGHT_MOTOR);
              BUTTON_SetText(_aSingleButton[RStartBtn], "右开始");
              EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], "0");
            }
          }
          else
          {
            BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
            BUTTON_SetText(hItem, "停止");
            if (!GetMotorConfig(REAL_LEFT_SPEED)) // If the left motor is not operating
            {
              StartSpecificMotor(LEFT_MOTOR);
              BUTTON_SetText(_aSingleButton[LStartBtn], "左停止");
              EDIT_SetText(_aSingleEdit[REAL_LEFT_SPEED], Int2String((int)(-GetMotorConfig(REAL_LEFT_SPEED) + 5500), str));
            }

            if (!GetMotorConfig(REAL_RIGHT_SPEED)) // If the right motor is not operating
            {
              BUTTON_SetText(_aSingleButton[RStartBtn], "右停止");
              StartSpecificMotor(RIGHT_MOTOR);
              EDIT_SetText(_aSingleEdit[REAL_RIGHT_SPEED], Int2String((int)(-GetMotorConfig(REAL_RIGHT_SPEED) + 5500), str));
            }
          }
        }
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'ModeBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        WM_HideWindow(SingCtrl_Win);
        WM_ShowWindow(DualCtrl_Win);

        if (GetMotorConfig(REAL_LEFT_SPEED))
        {
          EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], Int2String(-GetMotorConfig(REAL_LEFT_SPEED) + 5500, str));
        }
        else 
        {
          EDIT_SetText(_aDualEdit[REAL_LEFT_SPEED], "0");
        }

        if (GetMotorConfig(REAL_RIGHT_SPEED))
        {
          EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], Int2String(-GetMotorConfig(REAL_RIGHT_SPEED) + 5500, str));
        }
        else 
        {
          EDIT_SetText(_aDualEdit[REAL_RIGHT_SPEED], "0");
        }

        if (GetMotorConfig(REAL_LEFT_SPEED) || GetMotorConfig(REAL_RIGHT_SPEED))
        {
          BUTTON_SetText(_aDualButton[DualStartBtn], "停止");
        }
        else
        {
          BUTTON_SetText(_aDualButton[DualStartBtn], "开始");
        }

        value = SLIDER_GetValue(DualSlider);
        SetMotorConfig(SET_LEFT_SPEED, -value + 5500);
        SetMotorConfig(SET_RIGHT_SPEED, -value + 5500);
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'DirBtn'
      switch (NCode)
      {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        ChangeDirection();
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
        BUTTON_SetFont(hItem, &GUI_FontMSBlack24);
        if (GetMotorConfig(DIRECTION))
        {
          BUTTON_SetText(_aDualButton[DirBtn], "两侧拉伸");
          BUTTON_SetText(_aSingleButton[DirBtn], "两侧拉伸");
        }
        else
        {
          BUTTON_SetText(_aDualButton[DirBtn], "靠近中心");
          BUTTON_SetText(_aSingleButton[DirBtn], "靠近中心");
        }
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
        // USER START (Optionally insert additional code for further notification handling)
        // USER END
      }
      break;
      // USER START (Optionally insert additional code for further Ids)
      // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
 *
 *       Public code
 *
 **********************************************************************
 */
/*********************************************************************
 *
 *       CreateSingCtrl_Win
 */
WM_HWIN CreateSingCtrl_Win(void);
WM_HWIN CreateSingCtrl_Win(void)
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
