/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font Converter for emWin version 5.28                       *
*        Compiled Jan 30 2015, 16:40:45                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MSBlack24.c                                           *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMSBlack24;

/* Start of unicode area <Geometric Shapes> */
GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_25B2[ 24] = { /* code 25B2, BLACK UP-POINTING TRIANGLE */
  ________,________,
  _____XX_,________,
  _____XX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_25BC[ 24] = { /* code 25BC, BLACK DOWN-POINTING TRIANGLE */
  XXXXXXXX,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  _____XX_,________,
  _____XX_,________,
  ________,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_4E24[ 30] = { /* code 4E24 */
  XXXXXXXX,XXXXXXXX,
  _____X__,__X_____,
  _____X__,__X_____,
  _XXXXXXX,XXXXXXX_,
  _X___X__,__X___X_,
  _X___X__,__X___X_,
  _X___X__,__X___X_,
  _X__XXX_,__X___X_,
  _X__X_X_,_XXX__X_,
  _X_XX__X,_X_XX_X_,
  _X_X____,X____XX_,
  _XX____X,X_____X_,
  _X_____X,______X_,
  _X______,______X_,
  _X______,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_4E2D[ 34] = { /* code 4E2D */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  X______X,______X_,
  X______X,______X_,
  X______X,______X_,
  X______X,______X_,
  X______X,______X_,
  XXXXXXXX,XXXXXXX_,
  X______X,______X_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_4F38[ 34] = { /* code 4F38 */
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXXX,
  __X___X_,__X____X,
  __X___X_,__X____X,
  _XX___X_,__X____X,
  _XX___XX,XXXXXXXX,
  X_X___X_,__X____X,
  X_X___X_,__X____X,
  __X___X_,__X____X,
  __X___XX,XXXXXXXX,
  __X___X_,__X____X,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_4FA7[ 51] = { /* code 4FA7 */
  ___X____,________,X_______,
  ___X_XXX,XXX_____,X_______,
  __XX_X__,__X__X__,X_______,
  __X__X__,X_X__X__,X_______,
  __X__X__,X_X__X__,X_______,
  _XX__X__,X_X__X__,X_______,
  _XX__X__,X_X__X__,X_______,
  _XX__X__,X_X__X__,X_______,
  X_X__X__,X_X__X__,X_______,
  X_X__X__,X_X__X__,X_______,
  __X__X__,X_X__X__,X_______,
  __X__X__,X_X__X__,X_______,
  __X____X,X____X__,X_______,
  __X____X,_XX_____,X_______,
  __X___X_,__XX____,X_______,
  __X__XX_,________,X_______,
  __X_XX__,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_505C[ 34] = { /* code 505C */
  ___X____,_X______,
  ___X____,__X_____,
  __XXXXXX,XXXXXXXX,
  __X_____,________,
  __X___XX,XXXXXX__,
  __X___X_,_____X__,
  _XX___XX,XXXXXX__,
  _XX___X_,_____X__,
  X_X_____,________,
  X_X_XXXX,XXXXXXXX,
  __X_X___,_______X,
  __X___XX,XXXXXX__,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X_____,__X_____,
  __X____X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5149[ 48] = { /* code 5149 */
  ________,X_______,________,
  __X_____,X______X,________,
  ___X____,X_____X_,________,
  ___XX___,X____X__,________,
  ____XX__,X___X___,________,
  _____X__,X__X____,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ______X_,__X_____,________,
  ______X_,__X_____,________,
  ______X_,__X_____,________,
  _____X__,__X_____,________,
  _____X__,__X_____,X_______,
  ____X___,__X_____,X_______,
  __XX____,__X_____,X_______,
  XX______,___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5355[ 51] = { /* code 5355 */
  ____X___,_____X__,________,
  ____XX__,____X___,________,
  _____XX_,___X____,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,X______X,________,
  __X_____,X______X,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,X______X,________,
  __X_____,X______X,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,X______X,________,
  ________,X_______,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_53CC[ 48] = { /* code 53CC */
  XXXXXXXX,_XXXXXXX,X_______,
  _______X,_X______,X_______,
  X______X,_X______,X_______,
  _X_____X,_X______,X_______,
  _XX___X_,_XX____X,________,
  __X___X_,__X____X,________,
  ___X_XX_,__X____X,________,
  ___XXX__,__XX__X_,________,
  ____XX__,___X__X_,________,
  ____XX__,___XXX__,________,
  ___XXXX_,____XX__,________,
  ___X__X_,____XX__,________,
  __X___XX,___X_XX_,________,
  _X_____X,_XX___XX,________,
  X_______,XX_____X,X_______,
  ______XX,________,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_53D8[ 48] = { /* code 53D8 */
  _______X,X_______,________,
  ________,XX______,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ______X_,__X_____,________,
  ___X__X_,__X__X__,________,
  __XX__X_,__X___X_,________,
  _XX___X_,__X___XX,________,
  XX____X_,__X____X,X_______,
  X_______,________,X_______,
  __XXXXXX,XXXXXX__,________,
  ____X___,____X___,________,
  _____X__,__XX____,________,
  ______XX,XXX_____,________,
  _______X,XX______,________,
  ____XXX_,_XXXX___,________,
  XXXX____,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_53F3[ 54] = { /* code 53F3 */
  ________,X_______,________,
  _______X,________,________,
  _______X,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  ______X_,________,________,
  _____X__,________,________,
  _____X__,________,________,
  ____X___,________,________,
  ___XXXXX,XXXXXXXX,________,
  ___XX___,_______X,________,
  __XXX___,_______X,________,
  _XX_X___,_______X,________,
  XX__X___,_______X,________,
  X___X___,_______X,________,
  ____X___,_______X,________,
  ____XXXX,XXXXXXXX,________,
  ____X___,_______X,________,
  ____X___,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5411[ 34] = { /* code 5411 */
  ______X_,________,
  _____X__,________,
  _____X__,________,
  XXXXXXXX,XXXXXX__,
  X_______,_____X__,
  X_______,_____X__,
  X_______,_____X__,
  X___XXXX,XX___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___X___,_X___X__,
  X___XXXX,XX___X__,
  X___X___,_____X__,
  X_______,_____X__,
  X_______,_____X__,
  X_______,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_59CB[ 51] = { /* code 59CB */
  ___X____,___X____,________,
  ___X____,__XX____,________,
  ___X____,__X___X_,________,
  __X_____,_XX___XX,________,
  XXXXXXX_,_X_____X,________,
  __X___X_,XX_____X,X_______,
  __X___X_,XXXXXXXX,X_______,
  _X____XX,XX______,XX______,
  _X___XX_,________,_X______,
  _X___X__,________,________,
  _XX__X__,XXXXXXXX,X_______,
  ___XXX__,X_______,X_______,
  ____X___,X_______,X_______,
  ___X_X__,X_______,X_______,
  __X___X_,X_______,X_______,
  _X______,XXXXXXXX,X_______,
  X_______,X_______,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5B9A[ 51] = { /* code 5B9A */
  _______X,________,________,
  _______X,X_______,________,
  _XXXXXXX,XXXXXXXX,________,
  _X______,_______X,________,
  _X______,_______X,________,
  ________,________,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  ___X____,X_______,________,
  ___X____,X_______,________,
  ___X____,XXXXXXXX,________,
  __XX____,X_______,________,
  __XX____,X_______,________,
  __XXX___,X_______,________,
  _X__XXX_,X_______,________,
  _X____XX,XXXXXXXX,X_______,
  X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5B9E[ 51] = { /* code 5B9E */
  ________,X_______,________,
  ________,XX______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _X______,________,X_______,
  _X__X___,_X______,X_______,
  _____X__,_X______,________,
  ______X_,_X______,________,
  __XX___X,_X______,________,
  ____XX__,_X______,________,
  _____XX_,_X______,________,
  ________,_X______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,XX______,________,
  _______X,XXXX____,________,
  ______XX,___XXX__,________,
  ___XXX__,_____XXX,________,
  XXX_____,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5DE6[ 48] = { /* code 5DE6 */
  ______X_,________,________,
  ______X_,________,________,
  _____X__,________,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _____X__,________,________,
  _____X__,________,________,
  ____X___,________,________,
  ____X___,________,________,
  ____XXXX,XXXXXXXX,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  __X_____,_X______,________,
  __X_____,_X______,________,
  _X______,_X______,________,
  _X______,_X______,________,
  X__XXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5F00[ 48] = { /* code 5F00 */
  _XXXXXXX,XXXXXXXX,X_______,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  XXXXXXXX,XXXXXXXX,XX______,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  ____X___,____X___,________,
  ___XX___,____X___,________,
  __XX____,____X___,________,
  _XX_____,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5F0F[ 51] = { /* code 5F0F */
  ________,___X__X_,________,
  ________,___X___X,X_______,
  ________,___X___X,________,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  _XXXXXXX,XX_X____,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____XX__,__X_____,
  _____X_X,XXX__X__,__X_____,
  ___XXXX_,_____XX_,__X_____,
  XXX_____,______XX,_X______,
  ________,_______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_5FC3[ 48] = { /* code 5FC3 */
  ________,X_______,________,
  ________,X_______,________,
  ________,_X______,________,
  ________,_X______,________,
  _____X__,__X_____,________,
  _____X__,__X___X_,________,
  __X__X__,_______X,________,
  __X__X__,_______X,________,
  _X___X__,________,X_______,
  _X___X__,________,XX______,
  XX___X__,________,_X______,
  X____X__,______X_,________,
  _____X__,______X_,________,
  _____X__,______X_,________,
  _____X__,_____X__,________,
  ______XX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_62C9[ 51] = { /* code 62C9 */
  ___X____,___X____,________,
  ___X____,___XX___,________,
  ___X____,____X___,________,
  ___X___X,XXXXXXXX,X_______,
  XXXXXX__,________,________,
  ___X____,X______X,________,
  ___X____,X______X,________,
  ___X____,_X_____X,________,
  ___X_XX_,_X____X_,________,
  __XXX___,_X____X_,________,
  XX_X____,_X____X_,________,
  ___X____,__X___X_,________,
  ___X____,__X__X__,________,
  ___X____,__X__X__,________,
  ___X____,_____X__,________,
  ___X__XX,XXXXXXXX,XX______,
  XXXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_673A[ 51] = { /* code 673A */
  ___X____,________,________,
  ___X____,XXXXXX__,________,
  ___X____,X____X__,________,
  XXXXXXX_,X____X__,________,
  ___X____,X____X__,________,
  __XX____,X____X__,________,
  __XXX___,X____X__,________,
  __XXXX__,X____X__,________,
  _X_X__X_,X____X__,________,
  _X_X____,X____X__,________,
  XX_X____,X____X__,________,
  X__X____,X____X__,_X______,
  ___X___X,_____X__,_X______,
  ___X___X,_____X__,_X______,
  ___X___X,_____X__,XX______,
  ___X__X_,_____XXX,X_______,
  ___X_XX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_6837[ 54] = { /* code 6837 */
  ___X____,X_______,________,
  ___X____,_X_____X,________,
  ___X____,_XX___X_,________,
  ___X____,__X__X__,________,
  XXXXXX_X,XXXXXXXX,X_______,
  ___X____,____X___,________,
  __XX____,____X___,________,
  __XXX___,____X___,________,
  __XXXX_X,XXXXXXXX,X_______,
  _X_X_XX_,____X___,________,
  _X_X__X_,____X___,________,
  X__X____,____X___,________,
  X__X__XX,XXXXXXXX,XX______,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_6A21[ 51] = { /* code 6A21 */
  ___X____,_X___X__,________,
  ___X____,_X___X__,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,_X___X__,________,
  XXXXXX__,_X___X__,________,
  ___X___X,XXXXXXXX,________,
  __XX___X,_______X,________,
  __XXX__X,XXXXXXXX,________,
  _XXX_X_X,_______X,________,
  _X_X___X,XXXXXXXX,________,
  XX_X___X,___X___X,________,
  X__X____,___X____,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,__XXX___,________,
  ___X____,_XX_X___,________,
  ___X___X,X____XX_,________,
  ___X_XX_,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_6B62[ 48] = { /* code 6B62 */
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_XXXXXXX,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  XXXXXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_7535[ 32] = { /* code 7535 */
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXX__,
  X______X,_____X__,
  X______X,_____X__,
  X______X,_____X__,
  XXXXXXXX,XXXXXX__,
  X______X,_____X__,
  X______X,_____X__,
  X______X,_____X__,
  XXXXXXXX,XXXXXX__,
  X______X,________,
  _______X,_______X,
  _______X,_______X,
  _______X,______XX,
  ________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_7EA4[ 48] = { /* code 7EA4 */
  ____X___,________,________,
  ___X____,_____XXX,X_______,
  ___X___X,XXXXX___,________,
  __X_____,____X___,________,
  _X____X_,____X___,________,
  XX___X__,____X___,________,
  XXXXX___,____X___,________,
  ___X____,____X___,________,
  __XX___X,XXXXXXXX,XX______,
  _X______,____X___,________,
  _XXXXXX_,____X___,________,
  XXX_____,____X___,________,
  ________,____X___,________,
  _____XX_,____X___,________,
  __XXX___,____X___,________,
  XX______,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_8BBE[ 48] = { /* code 8BBE */
  _X_____X,XXXXXX__,________,
  __X____X,_____X__,________,
  ___X___X,_____X__,________,
  ______XX,_____X__,________,
  _____XX_,_____XXX,X_______,
  XXX__X__,________,________,
  __X_____,________,________,
  __X__XXX,XXXXXXX_,________,
  __X____X,______X_,________,
  __X____X,X____X__,________,
  __X_____,X___XX__,________,
  __X_X___,_X_XX___,________,
  __XXX___,_XXX____,________,
  _XXX____,XX_XX___,________,
  _X___XXX,____XXX_,________,
  ___XXX__,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_8F6C[ 51] = { /* code 8F6C */
  ____X___,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  XXXXXXX_,XXXXXXXX,________,
  __X_____,__X_____,________,
  __X_X___,__X_____,________,
  _X__X___,_X______,________,
  _X__X__X,XXXXXXXX,X_______,
  X___X___,_X______,________,
  XXXXXXX_,X_______,________,
  ____X___,X_______,________,
  ____X_X_,XXXXXXXX,________,
  __XXXX__,______XX,________,
  XX__X___,XX___X__,________,
  ____X___,_XXXX___,________,
  ____X___,___XXX__,________,
  ____X___,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_8FD1[ 51] = { /* code 8FD1 */
  _X______,____XXXX,________,
  __X____X,XXXX____,________,
  ___X___X,________,________,
  ____X__X,________,________,
  _______X,________,________,
  _______X,________,________,
  XXX____X,XXXXXXXX,XX______,
  __X____X,_____X__,________,
  __X____X,_____X__,________,
  __X____X,_____X__,________,
  __X____X,_____X__,________,
  __X___X_,_____X__,________,
  __X___X_,_____X__,________,
  __X__XX_,_____X__,________,
  _XXX_X__,_____X__,________,
  XX_XX___,________,________,
  X____XXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_901F[ 51] = { /* code 901F */
  _X______,___X____,________,
  _XX_____,___X____,________,
  __X__XXX,XXXXXXXX,X_______,
  __XX____,___X____,________,
  ___X____,___X____,________,
  ______XX,XXXXXXXX,________,
  XXX___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___XX,XXXXXXXX,________,
  __X___X_,__XX___X,________,
  __X_____,_XXXX___,________,
  __X____X,X__X_XX_,________,
  __X___XX,___X__XX,________,
  __X_XX__,___X____,X_______,
  _XX_____,___X____,________,
  XX_XX___,________,________,
  X___XXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_91C7[ 54] = { /* code 91C7 */
  ________,____XXXX,________,
  __XXXXXX,XXXX____,________,
  _______X,_______X,________,
  __X____X,X_____XX,________,
  __XX____,X_____X_,________,
  ___X____,_X___X__,________,
  ___XX___,_X__XX__,________,
  ____X___,X___X___,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _______X,XX______,________,
  ______X_,X_X_____,________,
  _____X__,X__X____,________,
  ___XX___,X___XX__,________,
  __XX____,X_____XX,________,
  XX______,X_______,XX______,
  ________,X_______,________,
  ________,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_9525[ 51] = { /* code 9525 */
  __X_____,_X__X___,________,
  __X_____,XX__X___,________,
  _X______,X____X__,________,
  _XXXXX_X,X____X__,________,
  _X_____X,XXXXXXXX,X_______,
  X_____XX,____X___,________,
  XXXXX_XX,____X___,________,
  __X__X_X,XXXXXXXX,X_______,
  __X____X,____X___,________,
  __X____X,____X___,________,
  XXXXXX_X,____X___,________,
  __X____X,XXXXXXXX,X_______,
  __X____X,____X___,________,
  __X____X,____X___,________,
  __X__X_X,____X___,________,
  __XXX__X,XXXXXXXX,X_______,
  _XX____X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_9645[ 48] = { /* code 9645 */
  XXXX_XXX,XXXXXXXX,________,
  X__X____,________,________,
  X__X____,________,________,
  X_X_____,________,________,
  X_X_____,________,________,
  X_X__XXX,XXXXXXXX,X_______,
  X_X_____,__X_____,________,
  X__X____,__X_____,________,
  X__X____,X_X__X__,________,
  X__X___X,X_X___X_,________,
  X__X___X,__X___X_,________,
  X__X__X_,__X____X,________,
  XXXX__X_,__X____X,X_______,
  X____X__,__X_____,X_______,
  X_______,__X_____,________,
  X______X,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontMSBlack24_9760[ 51] = { /* code 9760 */
  ___XX___,X_______,________,
  __XXXXXX,XXXXXXX_,________,
  _X______,X_______,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ________,________,________,
  __XXXXXX,XXXXXX__,________,
  __X_____,_____X__,________,
  __XXXXXX,XXXXXX__,________,
  __X_____,_____X__,________,
  ______X_,__X_____,________,
  XXXXXXX_,__XXXXXX,________,
  ______X_,__X_____,________,
  _XXXXXX_,__XXXXXX,________,
  ______X_,__X_____,________,
  XXXXXXX_,__XXXXXX,X_______,
  ______X_,__X_____,________,
  ______X_,__X_____,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontMSBlack24_CharInfo[35] = {
   {  12,  12,   3,   7,  18, acGUI_FontMSBlack24_25B2 } /* code 25B2, BLACK UP-POINTING TRIANGLE */
  ,{  12,  12,   3,   7,  18, acGUI_FontMSBlack24_25BC } /* code 25BC, BLACK DOWN-POINTING TRIANGLE */
  ,{  16,  15,   1,   5,  18, acGUI_FontMSBlack24_4E24 } /* code 4E24 */
  ,{  15,  17,   1,   4,  18, acGUI_FontMSBlack24_4E2D } /* code 4E2D */
  ,{  16,  17,   0,   4,  18, acGUI_FontMSBlack24_4F38 } /* code 4F38 */
  ,{  17,  17,   0,   4,  18, acGUI_FontMSBlack24_4FA7 } /* code 4FA7 */
  ,{  16,  17,   1,   4,  18, acGUI_FontMSBlack24_505C } /* code 505C */
  ,{  17,  16,   0,   4,  18, acGUI_FontMSBlack24_5149 } /* code 5149 */
  ,{  18,  17,   0,   4,  18, acGUI_FontMSBlack24_5355 } /* code 5355 */
  ,{  18,  16,   0,   5,  18, acGUI_FontMSBlack24_53CC } /* code 53CC */
  ,{  17,  16,   0,   4,  18, acGUI_FontMSBlack24_53D8 } /* code 53D8 */
  ,{  18,  18,   0,   4,  18, acGUI_FontMSBlack24_53F3 } /* code 53F3 */
  ,{  14,  17,   2,   4,  18, acGUI_FontMSBlack24_5411 } /* code 5411 */
  ,{  18,  17,   0,   4,  18, acGUI_FontMSBlack24_59CB } /* code 59CB */
  ,{  17,  17,   0,   4,  18, acGUI_FontMSBlack24_5B9A } /* code 5B9A */
  ,{  17,  17,   0,   4,  18, acGUI_FontMSBlack24_5B9E } /* code 5B9E */
  ,{  17,  16,   1,   4,  18, acGUI_FontMSBlack24_5DE6 } /* code 5DE6 */
  ,{  18,  16,   0,   5,  18, acGUI_FontMSBlack24_5F00 } /* code 5F00 */
  ,{  19,  17,  -1,   4,  18, acGUI_FontMSBlack24_5F0F } /* code 5F0F */
  ,{  18,  16,   0,   4,  18, acGUI_FontMSBlack24_5FC3 } /* code 5FC3 */
  ,{  18,  17,   0,   4,  18, acGUI_FontMSBlack24_62C9 } /* code 62C9 */
  ,{  18,  17,   0,   4,  18, acGUI_FontMSBlack24_673A } /* code 673A */
  ,{  18,  18,   0,   4,  18, acGUI_FontMSBlack24_6837 } /* code 6837 */
  ,{  17,  17,   0,   4,  18, acGUI_FontMSBlack24_6A21 } /* code 6A21 */
  ,{  17,  16,   1,   4,  18, acGUI_FontMSBlack24_6B62 } /* code 6B62 */
  ,{  16,  16,   1,   4,  18, acGUI_FontMSBlack24_7535 } /* code 7535 */
  ,{  18,  16,   0,   4,  18, acGUI_FontMSBlack24_7EA4 } /* code 7EA4 */
  ,{  17,  16,   1,   5,  18, acGUI_FontMSBlack24_8BBE } /* code 8BBE */
  ,{  17,  17,   1,   4,  18, acGUI_FontMSBlack24_8F6C } /* code 8F6C */
  ,{  18,  17,   0,   4,  18, acGUI_FontMSBlack24_8FD1 } /* code 8FD1 */
  ,{  17,  17,   0,   4,  18, acGUI_FontMSBlack24_901F } /* code 901F */
  ,{  18,  18,   0,   4,  18, acGUI_FontMSBlack24_91C7 } /* code 91C7 */
  ,{  17,  17,   0,   4,  18, acGUI_FontMSBlack24_9525 } /* code 9525 */
  ,{  17,  16,   1,   5,  18, acGUI_FontMSBlack24_9645 } /* code 9645 */
  ,{  17,  17,   1,   4,  18, acGUI_FontMSBlack24_9760 } /* code 9760 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop35 = {
   0x9760 /* first character */
  ,0x9760 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 34] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop34 = {
   0x9645 /* first character */
  ,0x9645 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 33] /* address of first character */
  ,&GUI_FontMSBlack24_Prop35 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop33 = {
   0x9525 /* first character */
  ,0x9525 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 32] /* address of first character */
  ,&GUI_FontMSBlack24_Prop34 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop32 = {
   0x91C7 /* first character */
  ,0x91C7 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 31] /* address of first character */
  ,&GUI_FontMSBlack24_Prop33 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop31 = {
   0x901F /* first character */
  ,0x901F /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 30] /* address of first character */
  ,&GUI_FontMSBlack24_Prop32 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop30 = {
   0x8FD1 /* first character */
  ,0x8FD1 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 29] /* address of first character */
  ,&GUI_FontMSBlack24_Prop31 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop29 = {
   0x8F6C /* first character */
  ,0x8F6C /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 28] /* address of first character */
  ,&GUI_FontMSBlack24_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop28 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 27] /* address of first character */
  ,&GUI_FontMSBlack24_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop27 = {
   0x7EA4 /* first character */
  ,0x7EA4 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 26] /* address of first character */
  ,&GUI_FontMSBlack24_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop26 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 25] /* address of first character */
  ,&GUI_FontMSBlack24_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop25 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 24] /* address of first character */
  ,&GUI_FontMSBlack24_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop24 = {
   0x6A21 /* first character */
  ,0x6A21 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 23] /* address of first character */
  ,&GUI_FontMSBlack24_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop23 = {
   0x6837 /* first character */
  ,0x6837 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 22] /* address of first character */
  ,&GUI_FontMSBlack24_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop22 = {
   0x673A /* first character */
  ,0x673A /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 21] /* address of first character */
  ,&GUI_FontMSBlack24_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop21 = {
   0x62C9 /* first character */
  ,0x62C9 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 20] /* address of first character */
  ,&GUI_FontMSBlack24_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop20 = {
   0x5FC3 /* first character */
  ,0x5FC3 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 19] /* address of first character */
  ,&GUI_FontMSBlack24_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop19 = {
   0x5F0F /* first character */
  ,0x5F0F /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 18] /* address of first character */
  ,&GUI_FontMSBlack24_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop18 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 17] /* address of first character */
  ,&GUI_FontMSBlack24_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop17 = {
   0x5DE6 /* first character */
  ,0x5DE6 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 16] /* address of first character */
  ,&GUI_FontMSBlack24_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop16 = {
   0x5B9E /* first character */
  ,0x5B9E /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 15] /* address of first character */
  ,&GUI_FontMSBlack24_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop15 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 14] /* address of first character */
  ,&GUI_FontMSBlack24_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop14 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 13] /* address of first character */
  ,&GUI_FontMSBlack24_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop13 = {
   0x5411 /* first character */
  ,0x5411 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 12] /* address of first character */
  ,&GUI_FontMSBlack24_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop12 = {
   0x53F3 /* first character */
  ,0x53F3 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 11] /* address of first character */
  ,&GUI_FontMSBlack24_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop11 = {
   0x53D8 /* first character */
  ,0x53D8 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[ 10] /* address of first character */
  ,&GUI_FontMSBlack24_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop10 = {
   0x53CC /* first character */
  ,0x53CC /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  9] /* address of first character */
  ,&GUI_FontMSBlack24_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop9 = {
   0x5355 /* first character */
  ,0x5355 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  8] /* address of first character */
  ,&GUI_FontMSBlack24_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop8 = {
   0x5149 /* first character */
  ,0x5149 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  7] /* address of first character */
  ,&GUI_FontMSBlack24_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop7 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  6] /* address of first character */
  ,&GUI_FontMSBlack24_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop6 = {
   0x4FA7 /* first character */
  ,0x4FA7 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  5] /* address of first character */
  ,&GUI_FontMSBlack24_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop5 = {
   0x4F38 /* first character */
  ,0x4F38 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  4] /* address of first character */
  ,&GUI_FontMSBlack24_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop4 = {
   0x4E2D /* first character */
  ,0x4E2D /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  3] /* address of first character */
  ,&GUI_FontMSBlack24_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop3 = {
   0x4E24 /* first character */
  ,0x4E24 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  2] /* address of first character */
  ,&GUI_FontMSBlack24_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop2 = {
   0x25BC /* first character */
  ,0x25BC /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  1] /* address of first character */
  ,&GUI_FontMSBlack24_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMSBlack24_Prop1 = {
   0x25B2 /* first character */
  ,0x25B2 /* last character  */
  ,&GUI_FontMSBlack24_CharInfo[  0] /* address of first character */
  ,&GUI_FontMSBlack24_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMSBlack24 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMSBlack24_Prop1}
  ,19 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

